//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Urban.ATC.CommonView.Properties {
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resource1 {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Urban.ATC.CommonView.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap AR_active {
            get {
                object obj = ResourceManager.GetObject("AR_active", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap AR_offered {
            get {
                object obj = ResourceManager.GetObject("AR_offered", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap ATO_fault {
            get {
                object obj = ResourceManager.GetObject("ATO_fault", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap ATP_fault {
            get {
                object obj = ResourceManager.GetObject("ATP_fault", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap braking {
            get {
                object obj = ResourceManager.GetObject("braking", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Button_s__disturbed {
            get {
                object obj = ResourceManager.GetObject("Button_s__disturbed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Button_s__disturbed2 {
            get {
                object obj = ResourceManager.GetObject("Button_s__disturbed2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap chemenpanglu {
            get {
                object obj = ResourceManager.GetObject("chemenpanglu", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap chemenzhuangtai1 {
            get {
                object obj = ResourceManager.GetObject("chemenzhuangtai1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap chemenzhuangtai2 {
            get {
                object obj = ResourceManager.GetObject("chemenzhuangtai2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap chemenzhuangtai3 {
            get {
                object obj = ResourceManager.GetObject("chemenzhuangtai3", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap chemenzhuangtai4 {
            get {
                object obj = ResourceManager.GetObject("chemenzhuangtai4", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap chemenzhuangtai5 {
            get {
                object obj = ResourceManager.GetObject("chemenzhuangtai5", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap chemenzhuangtai6 {
            get {
                object obj = ResourceManager.GetObject("chemenzhuangtai6", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap chemenzhuangtai7 {
            get {
                object obj = ResourceManager.GetObject("chemenzhuangtai7", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap closed_and_locked_1 {
            get {
                object obj = ResourceManager.GetObject("closed_and_locked_1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap closed_and_locked_2 {
            get {
                object obj = ResourceManager.GetObject("closed_and_locked_2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap closed_and_locked_3 {
            get {
                object obj = ResourceManager.GetObject("closed_and_locked_3", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap closed_and_locked_4 {
            get {
                object obj = ResourceManager.GetObject("closed_and_locked_4", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap closed_and_locked_5 {
            get {
                object obj = ResourceManager.GetObject("closed_and_locked_5", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap closed_and_locked_6 {
            get {
                object obj = ResourceManager.GetObject("closed_and_locked_6", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap coasting {
            get {
                object obj = ResourceManager.GetObject("coasting", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Departure_Request {
            get {
                object obj = ResourceManager.GetObject("Departure_Request", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Depot_Driver {
            get {
                object obj = ResourceManager.GetObject("Depot_Driver", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Depot_Entry {
            get {
                object obj = ResourceManager.GetObject("Depot_Entry", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap dingwei1 {
            get {
                object obj = ResourceManager.GetObject("dingwei1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap dingwei2 {
            get {
                object obj = ResourceManager.GetObject("dingwei2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Door_Close_Order {
            get {
                object obj = ResourceManager.GetObject("Door_Close_Order", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap DTRO_active {
            get {
                object obj = ResourceManager.GetObject("DTRO_active", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap DTRO_is_offered {
            get {
                object obj = ResourceManager.GetObject("DTRO_is_offered", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Emergency_Brake {
            get {
                object obj = ResourceManager.GetObject("Emergency_Brake", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Emergency_Brake2 {
            get {
                object obj = ResourceManager.GetObject("Emergency_Brake2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap GreenRound {
            get {
                object obj = ResourceManager.GetObject("GreenRound", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap HOLD {
            get {
                object obj = ResourceManager.GetObject("HOLD", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Inside_Stopping_window {
            get {
                object obj = ResourceManager.GetObject("Inside_Stopping_window", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap jingbao1 {
            get {
                object obj = ResourceManager.GetObject("jingbao1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap jingbao2 {
            get {
                object obj = ResourceManager.GetObject("jingbao2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap jingzhi {
            get {
                object obj = ResourceManager.GetObject("jingzhi", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap kaimen1 {
            get {
                object obj = ResourceManager.GetObject("kaimen1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap kaimen2 {
            get {
                object obj = ResourceManager.GetObject("kaimen2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap kaimen3 {
            get {
                object obj = ResourceManager.GetObject("kaimen3", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap kongzhuan {
            get {
                object obj = ResourceManager.GetObject("kongzhuan", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap liangdu {
            get {
                object obj = ResourceManager.GetObject("liangdu", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap logo1 {
            get {
                object obj = ResourceManager.GetObject("logo1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap menshi1 {
            get {
                object obj = ResourceManager.GetObject("menshi1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap menshi2 {
            get {
                object obj = ResourceManager.GetObject("menshi2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap menu {
            get {
                object obj = ResourceManager.GetObject("menu", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap motoring {
            get {
                object obj = ResourceManager.GetObject("motoring", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap motoring1 {
            get {
                object obj = ResourceManager.GetObject("motoring1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap mubiaojuli {
            get {
                object obj = ResourceManager.GetObject("mubiaojuli", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap No_door_supervision {
            get {
                object obj = ResourceManager.GetObject("No_door_supervision", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap No_WCURadio_link {
            get {
                object obj = ResourceManager.GetObject("No_WCURadio_link", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap OBCD_Green_Green {
            get {
                object obj = ResourceManager.GetObject("OBCD_Green_Green", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap OBCD_Green_Red {
            get {
                object obj = ResourceManager.GetObject("OBCD_Green_Red", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap OBCD_Green_White {
            get {
                object obj = ResourceManager.GetObject("OBCD_Green_White", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap OBCD_Red_Green {
            get {
                object obj = ResourceManager.GetObject("OBCD_Red_Green", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap OBCD_Red_Red {
            get {
                object obj = ResourceManager.GetObject("OBCD_Red_Red", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap OBCD_White_Green {
            get {
                object obj = ResourceManager.GetObject("OBCD_White_Green", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap OBCD_White_Red {
            get {
                object obj = ResourceManager.GetObject("OBCD_White_Red", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Open_Both {
            get {
                object obj = ResourceManager.GetObject("Open_Both", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Open_Left {
            get {
                object obj = ResourceManager.GetObject("Open_Left", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Open_Left_first {
            get {
                object obj = ResourceManager.GetObject("Open_Left_first", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Open_Right {
            get {
                object obj = ResourceManager.GetObject("Open_Right", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Open_Right_first {
            get {
                object obj = ResourceManager.GetObject("Open_Right_first", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Outside_stopping_window {
            get {
                object obj = ResourceManager.GetObject("Outside_stopping_window", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Permissiver_door_release {
            get {
                object obj = ResourceManager.GetObject("Permissiver_door_release", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap PSD_not_closed {
            get {
                object obj = ResourceManager.GetObject("PSD_not_closed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap red {
            get {
                object obj = ResourceManager.GetObject("red", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap redqiu {
            get {
                object obj = ResourceManager.GetObject("redqiu", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap RedRound {
            get {
                object obj = ResourceManager.GetObject("RedRound", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Relesase_Speed {
            get {
                object obj = ResourceManager.GetObject("Relesase_Speed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap RST_Braking_pressure_not_ok {
            get {
                object obj = ResourceManager.GetObject("RST_Braking_pressure_not_ok", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap SKIP {
            get {
                object obj = ResourceManager.GetObject("SKIP", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Slip_or_Slide {
            get {
                object obj = ResourceManager.GetObject("Slip_or_Slide", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap tingche1 {
            get {
                object obj = ResourceManager.GetObject("tingche1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap tingche2 {
            get {
                object obj = ResourceManager.GetObject("tingche2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap tingche3 {
            get {
                object obj = ResourceManager.GetObject("tingche3", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap tongxin1 {
            get {
                object obj = ResourceManager.GetObject("tongxin1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap tongxin2 {
            get {
                object obj = ResourceManager.GetObject("tongxin2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Train_Integrity_not_ok {
            get {
                object obj = ResourceManager.GetObject("Train_Integrity_not_ok", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap Train_Integrity_ok {
            get {
                object obj = ResourceManager.GetObject("Train_Integrity_ok", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap wanzhengxing1 {
            get {
                object obj = ResourceManager.GetObject("wanzhengxing1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap wanzhengxing2 {
            get {
                object obj = ResourceManager.GetObject("wanzhengxing2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap yellow {
            get {
                object obj = ResourceManager.GetObject("yellow", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap zhizhen {
            get {
                object obj = ResourceManager.GetObject("zhizhen", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap zhizhen2 {
            get {
                object obj = ResourceManager.GetObject("zhizhen2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap zhizhen3 {
            get {
                object obj = ResourceManager.GetObject("zhizhen3", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap zhizhenhong {
            get {
                object obj = ResourceManager.GetObject("zhizhenhong", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap zhizhenhuang {
            get {
                object obj = ResourceManager.GetObject("zhizhenhuang", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap zhizhenhui {
            get {
                object obj = ResourceManager.GetObject("zhizhenhui", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
