//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urban.Iran.HMI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_GB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_GB() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Urban.Iran.HMI.Resource_GB", typeof(Resource_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Main menu 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Doors 的本地化字符串。
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        internal static string String100 {
            get {
                return ResourceManager.GetString("String100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station name 的本地化字符串。
        /// </summary>
        internal static string String101 {
            get {
                return ResourceManager.GetString("String101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrive Broadcast 的本地化字符串。
        /// </summary>
        internal static string String102 {
            get {
                return ResourceManager.GetString("String102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depart Broadcast 的本地化字符串。
        /// </summary>
        internal static string String103 {
            get {
                return ResourceManager.GetString("String103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Broadcast 的本地化字符串。
        /// </summary>
        internal static string String104 {
            get {
                return ResourceManager.GetString("String104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start station 的本地化字符串。
        /// </summary>
        internal static string String105 {
            get {
                return ResourceManager.GetString("String105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next station 的本地化字符串。
        /// </summary>
        internal static string String106 {
            get {
                return ResourceManager.GetString("String106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End station 的本地化字符串。
        /// </summary>
        internal static string String107 {
            get {
                return ResourceManager.GetString("String107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string String108 {
            get {
                return ResourceManager.GetString("String108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip Station 的本地化字符串。
        /// </summary>
        internal static string String109 {
            get {
                return ResourceManager.GetString("String109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brakes/Air 的本地化字符串。
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic 的本地化字符串。
        /// </summary>
        internal static string String110 {
            get {
                return ResourceManager.GetString("String110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 service delay 的本地化字符串。
        /// </summary>
        internal static string String111 {
            get {
                return ResourceManager.GetString("String111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vehicle faulty 的本地化字符串。
        /// </summary>
        internal static string String112 {
            get {
                return ResourceManager.GetString("String112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evacuate passengers 的本地化字符串。
        /// </summary>
        internal static string String113 {
            get {
                return ResourceManager.GetString("String113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string String114 {
            get {
                return ResourceManager.GetString("String114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic 的本地化字符串。
        /// </summary>
        internal static string String115 {
            get {
                return ResourceManager.GetString("String115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Public announcement 的本地化字符串。
        /// </summary>
        internal static string String116 {
            get {
                return ResourceManager.GetString("String116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop announcement 的本地化字符串。
        /// </summary>
        internal static string String117 {
            get {
                return ResourceManager.GetString("String117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string String118 {
            get {
                return ResourceManager.GetString("String118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current announcement 的本地化字符串。
        /// </summary>
        internal static string String119 {
            get {
                return ResourceManager.GetString("String119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prop/Aux/Battery 的本地化字符串。
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Car 的本地化字符串。
        /// </summary>
        internal static string String120 {
            get {
                return ResourceManager.GetString("String120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority 的本地化字符串。
        /// </summary>
        internal static string String121 {
            get {
                return ResourceManager.GetString("String121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string String122 {
            get {
                return ResourceManager.GetString("String122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date/Time 的本地化字符串。
        /// </summary>
        internal static string String123 {
            get {
                return ResourceManager.GetString("String123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event code 的本地化字符串。
        /// </summary>
        internal static string String124 {
            get {
                return ResourceManager.GetString("String124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Propulsion 的本地化字符串。
        /// </summary>
        internal static string String125 {
            get {
                return ResourceManager.GetString("String125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control &amp; Communic. 的本地化字符串。
        /// </summary>
        internal static string String126 {
            get {
                return ResourceManager.GetString("String126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auxiliary &amp; Battery 的本地化字符串。
        /// </summary>
        internal static string String127 {
            get {
                return ResourceManager.GetString("String127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit 的本地化字符串。
        /// </summary>
        internal static string String128 {
            get {
                return ResourceManager.GetString("String128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string String129 {
            get {
                return ResourceManager.GetString("String129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HVAC 的本地化字符串。
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string String130 {
            get {
                return ResourceManager.GetString("String130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string String131 {
            get {
                return ResourceManager.GetString("String131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door not programmed/faulty 的本地化字符串。
        /// </summary>
        internal static string String132 {
            get {
                return ResourceManager.GetString("String132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door programmed 的本地化字符串。
        /// </summary>
        internal static string String133 {
            get {
                return ResourceManager.GetString("String133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay time for door opening 的本地化字符串。
        /// </summary>
        internal static string String134 {
            get {
                return ResourceManager.GetString("String134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay time for door closing 的本地化字符串。
        /// </summary>
        internal static string String135 {
            get {
                return ResourceManager.GetString("String135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obstacle reclose delay 的本地化字符串。
        /// </summary>
        internal static string String136 {
            get {
                return ResourceManager.GetString("String136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open time 的本地化字符串。
        /// </summary>
        internal static string String137 {
            get {
                return ResourceManager.GetString("String137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 close time 的本地化字符串。
        /// </summary>
        internal static string String138 {
            get {
                return ResourceManager.GetString("String138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obstacle numbers before door open 的本地化字符串。
        /// </summary>
        internal static string String139 {
            get {
                return ResourceManager.GetString("String139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIS 的本地化字符串。
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening width on obstacle detection 的本地化字符串。
        /// </summary>
        internal static string String140 {
            get {
                return ResourceManager.GetString("String140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obstacle detection delay 的本地化字符串。
        /// </summary>
        internal static string String141 {
            get {
                return ResourceManager.GetString("String141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door obstacle close force  的本地化字符串。
        /// </summary>
        internal static string String142 {
            get {
                return ResourceManager.GetString("String142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acc./Ret. test 的本地化字符串。
        /// </summary>
        internal static string String143 {
            get {
                return ResourceManager.GetString("String143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master ctrl test 的本地化字符串。
        /// </summary>
        internal static string String144 {
            get {
                return ResourceManager.GetString("String144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill/Leak test 的本地化字符串。
        /// </summary>
        internal static string String145 {
            get {
                return ResourceManager.GetString("String145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acceleration 的本地化字符串。
        /// </summary>
        internal static string String146 {
            get {
                return ResourceManager.GetString("String146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inital speed 的本地化字符串。
        /// </summary>
        internal static string String147 {
            get {
                return ResourceManager.GetString("String147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final speed 的本地化字符串。
        /// </summary>
        internal static string String148 {
            get {
                return ResourceManager.GetString("String148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traction level 的本地化字符串。
        /// </summary>
        internal static string String149 {
            get {
                return ResourceManager.GetString("String149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Public announcement 的本地化字符串。
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retardation 的本地化字符串。
        /// </summary>
        internal static string String150 {
            get {
                return ResourceManager.GetString("String150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance 的本地化字符串。
        /// </summary>
        internal static string String151 {
            get {
                return ResourceManager.GetString("String151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake level 的本地化字符串。
        /// </summary>
        internal static string String152 {
            get {
                return ResourceManager.GetString("String152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change input value 的本地化字符串。
        /// </summary>
        internal static string String153 {
            get {
                return ResourceManager.GetString("String153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACC/RET 的本地化字符串。
        /// </summary>
        internal static string String154 {
            get {
                return ResourceManager.GetString("String154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCM/Mp1 的本地化字符串。
        /// </summary>
        internal static string String155 {
            get {
                return ResourceManager.GetString("String155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fwd 的本地化字符串。
        /// </summary>
        internal static string String156 {
            get {
                return ResourceManager.GetString("String156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rev 的本地化字符串。
        /// </summary>
        internal static string String157 {
            get {
                return ResourceManager.GetString("String157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCM/M 的本地化字符串。
        /// </summary>
        internal static string String158 {
            get {
                return ResourceManager.GetString("String158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCM/M2 的本地化字符串。
        /// </summary>
        internal static string String159 {
            get {
                return ResourceManager.GetString("String159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driveing direction 的本地化字符串。
        /// </summary>
        internal static string String160 {
            get {
                return ResourceManager.GetString("String160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master controller 的本地化字符串。
        /// </summary>
        internal static string String161 {
            get {
                return ResourceManager.GetString("String161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traction 的本地化字符串。
        /// </summary>
        internal static string String162 {
            get {
                return ResourceManager.GetString("String162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coasting 的本地化字符串。
        /// </summary>
        internal static string String163 {
            get {
                return ResourceManager.GetString("String163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake 的本地化字符串。
        /// </summary>
        internal static string String164 {
            get {
                return ResourceManager.GetString("String164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast brake 的本地化字符串。
        /// </summary>
        internal static string String165 {
            get {
                return ResourceManager.GetString("String165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passed 的本地化字符串。
        /// </summary>
        internal static string String166 {
            get {
                return ResourceManager.GetString("String166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        internal static string String167 {
            get {
                return ResourceManager.GetString("String167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        internal static string String168 {
            get {
                return ResourceManager.GetString("String168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inactive 的本地化字符串。
        /// </summary>
        internal static string String169 {
            get {
                return ResourceManager.GetString("String169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active events 的本地化字符串。
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activate Test 的本地化字符串。
        /// </summary>
        internal static string String170 {
            get {
                return ResourceManager.GetString("String170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filling test Elapsed time 的本地化字符串。
        /// </summary>
        internal static string String171 {
            get {
                return ResourceManager.GetString("String171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        internal static string String172 {
            get {
                return ResourceManager.GetString("String172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bars/hours 的本地化字符串。
        /// </summary>
        internal static string String173 {
            get {
                return ResourceManager.GetString("String173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pressure 的本地化字符串。
        /// </summary>
        internal static string String174 {
            get {
                return ResourceManager.GetString("String174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leakage test Elapsed time 的本地化字符串。
        /// </summary>
        internal static string String175 {
            get {
                return ResourceManager.GetString("String175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time remaining 的本地化字符串。
        /// </summary>
        internal static string String176 {
            get {
                return ResourceManager.GetString("String176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string String177 {
            get {
                return ResourceManager.GetString("String177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Farsi/…… 的本地化字符串。
        /// </summary>
        internal static string String178 {
            get {
                return ResourceManager.GetString("String178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English/…… 的本地化字符串。
        /// </summary>
        internal static string String179 {
            get {
                return ResourceManager.GetString("String179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ODBS status 的本地化字符串。
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display intensity 的本地化字符串。
        /// </summary>
        internal static string String180 {
            get {
                return ResourceManager.GetString("String180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your user id. 的本地化字符串。
        /// </summary>
        internal static string String181 {
            get {
                return ResourceManager.GetString("String181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master reset 的本地化字符串。
        /// </summary>
        internal static string String182 {
            get {
                return ResourceManager.GetString("String182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set wheel diameter 的本地化字符串。
        /// </summary>
        internal static string String183 {
            get {
                return ResourceManager.GetString("String183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block dyn. brake 的本地化字符串。
        /// </summary>
        internal static string String184 {
            get {
                return ResourceManager.GetString("String184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        internal static string String185 {
            get {
                return ResourceManager.GetString("String185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set date/time 的本地化字符串。
        /// </summary>
        internal static string String186 {
            get {
                return ResourceManager.GetString("String186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit Appl. 的本地化字符串。
        /// </summary>
        internal static string String187 {
            get {
                return ResourceManager.GetString("String187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string String188 {
            get {
                return ResourceManager.GetString("String188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current wheel diameter on reference axle 1 in Mp1 car 的本地化字符串。
        /// </summary>
        internal static string String189 {
            get {
                return ResourceManager.GetString("String189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comm.overview 的本地化字符串。
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set wheel diameter between 770 and 840 and  press Enter 的本地化字符串。
        /// </summary>
        internal static string String190 {
            get {
                return ResourceManager.GetString("String190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        internal static string String191 {
            get {
                return ResourceManager.GetString("String191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        internal static string String192 {
            get {
                return ResourceManager.GetString("String192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        internal static string String193 {
            get {
                return ResourceManager.GetString("String193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hour 的本地化字符串。
        /// </summary>
        internal static string String194 {
            get {
                return ResourceManager.GetString("String194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minute 的本地化字符串。
        /// </summary>
        internal static string String195 {
            get {
                return ResourceManager.GetString("String195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual time set 的本地化字符串。
        /// </summary>
        internal static string String196 {
            get {
                return ResourceManager.GetString("String196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency brake 的本地化字符串。
        /// </summary>
        internal static string String197 {
            get {
                return ResourceManager.GetString("String197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency applied 的本地化字符串。
        /// </summary>
        internal static string String198 {
            get {
                return ResourceManager.GetString("String198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Safety loop 的本地化字符串。
        /// </summary>
        internal static string String199 {
            get {
                return ResourceManager.GetString("String199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event history 的本地化字符串。
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maint.test 的本地化字符串。
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATC request 的本地化字符串。
        /// </summary>
        internal static string String200 {
            get {
                return ResourceManager.GetString("String200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dead man 的本地化字符串。
        /// </summary>
        internal static string String201 {
            get {
                return ResourceManager.GetString("String201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Train completeness 的本地化字符串。
        /// </summary>
        internal static string String202 {
            get {
                return ResourceManager.GetString("String202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traction block 的本地化字符串。
        /// </summary>
        internal static string String203 {
            get {
                return ResourceManager.GetString("String203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency brake 的本地化字符串。
        /// </summary>
        internal static string String204 {
            get {
                return ResourceManager.GetString("String204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MR pressure 的本地化字符串。
        /// </summary>
        internal static string String205 {
            get {
                return ResourceManager.GetString("String205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All doorstep closed 的本地化字符串。
        /// </summary>
        internal static string String206 {
            get {
                return ResourceManager.GetString("String206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master controller communication 的本地化字符串。
        /// </summary>
        internal static string String207 {
            get {
                return ResourceManager.GetString("String207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pantograph test 的本地化字符串。
        /// </summary>
        internal static string String208 {
            get {
                return ResourceManager.GetString("String208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overspeed 的本地化字符串。
        /// </summary>
        internal static string String209 {
            get {
                return ResourceManager.GetString("String209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operational data 的本地化字符串。
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major brake fault 的本地化字符串。
        /// </summary>
        internal static string String210 {
            get {
                return ResourceManager.GetString("String210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake isolated 的本地化字符串。
        /// </summary>
        internal static string String211 {
            get {
                return ResourceManager.GetString("String211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid cab status 的本地化字符串。
        /// </summary>
        internal static string String212 {
            get {
                return ResourceManager.GetString("String212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power cut off by DSD 的本地化字符串。
        /// </summary>
        internal static string String213 {
            get {
                return ResourceManager.GetString("String213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master controller test 的本地化字符串。
        /// </summary>
        internal static string String214 {
            get {
                return ResourceManager.GetString("String214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traction brake reference 的本地化字符串。
        /// </summary>
        internal static string String215 {
            get {
                return ResourceManager.GetString("String215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready to drive 的本地化字符串。
        /// </summary>
        internal static string String216 {
            get {
                return ResourceManager.GetString("String216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traction block 的本地化字符串。
        /// </summary>
        internal static string String217 {
            get {
                return ResourceManager.GetString("String217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Propulsion ok (at least one MCM ok) 的本地化字符串。
        /// </summary>
        internal static string String218 {
            get {
                return ResourceManager.GetString("String218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standstill 的本地化字符串。
        /// </summary>
        internal static string String219 {
            get {
                return ResourceManager.GetString("String219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software version 的本地化字符串。
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MC incoasting or braking 的本地化字符串。
        /// </summary>
        internal static string String220 {
            get {
                return ResourceManager.GetString("String220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driving direction 的本地化字符串。
        /// </summary>
        internal static string String221 {
            get {
                return ResourceManager.GetString("String221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Train MVB Communication 的本地化字符串。
        /// </summary>
        internal static string String222 {
            get {
                return ResourceManager.GetString("String222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both AXunit units ok in active cab 的本地化字符串。
        /// </summary>
        internal static string String223 {
            get {
                return ResourceManager.GetString("String223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid train speed 的本地化字符串。
        /// </summary>
        internal static string String224 {
            get {
                return ResourceManager.GetString("String224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max speed 的本地化字符串。
        /// </summary>
        internal static string String225 {
            get {
                return ResourceManager.GetString("String225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cars decoupled 的本地化字符串。
        /// </summary>
        internal static string String226 {
            get {
                return ResourceManager.GetString("String226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parking brake 的本地化字符串。
        /// </summary>
        internal static string String227 {
            get {
                return ResourceManager.GetString("String227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 left door release bypass 的本地化字符串。
        /// </summary>
        internal static string String228 {
            get {
                return ResourceManager.GetString("String228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right door release bypass 的本地化字符串。
        /// </summary>
        internal static string String229 {
            get {
                return ResourceManager.GetString("String229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door parameters 的本地化字符串。
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door interlock bypass 的本地化字符串。
        /// </summary>
        internal static string String230 {
            get {
                return ResourceManager.GetString("String230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery isolation switch 的本地化字符串。
        /// </summary>
        internal static string String231 {
            get {
                return ResourceManager.GetString("String231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MR low pressure bypass 的本地化字符串。
        /// </summary>
        internal static string String232 {
            get {
                return ResourceManager.GetString("String232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EB Train breaker 的本地化字符串。
        /// </summary>
        internal static string String233 {
            get {
                return ResourceManager.GetString("String233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal lighting circuit breaker 1 的本地化字符串。
        /// </summary>
        internal static string String234 {
            get {
                return ResourceManager.GetString("String234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal lighting circuit breaker 2 的本地化字符串。
        /// </summary>
        internal static string String235 {
            get {
                return ResourceManager.GetString("String235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency lighting circuit breaker 的本地化字符串。
        /// </summary>
        internal static string String236 {
            get {
                return ResourceManager.GetString("String236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tail light circuit breaker 的本地化字符串。
        /// </summary>
        internal static string String237 {
            get {
                return ResourceManager.GetString("String237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation light circuit breaker 的本地化字符串。
        /// </summary>
        internal static string String238 {
            get {
                return ResourceManager.GetString("String238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATC fault relay 的本地化字符串。
        /// </summary>
        internal static string String239 {
            get {
                return ResourceManager.GetString("String239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATC 的本地化字符串。
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Component/System 的本地化字符串。
        /// </summary>
        internal static string String240 {
            get {
                return ResourceManager.GetString("String240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string String241 {
            get {
                return ResourceManager.GetString("String241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operational data 的本地化字符串。
        /// </summary>
        internal static string String242 {
            get {
                return ResourceManager.GetString("String242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        internal static string String243 {
            get {
                return ResourceManager.GetString("String243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page 1 的本地化字符串。
        /// </summary>
        internal static string String244 {
            get {
                return ResourceManager.GetString("String244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page 2 的本地化字符串。
        /// </summary>
        internal static string String245 {
            get {
                return ResourceManager.GetString("String245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brakes &amp; Air legend 的本地化字符串。
        /// </summary>
        internal static string String246 {
            get {
                return ResourceManager.GetString("String246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Propulsion, Auxiliary and Battery lengend 的本地化字符串。
        /// </summary>
        internal static string String247 {
            get {
                return ResourceManager.GetString("String247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door parameter overview 的本地化字符串。
        /// </summary>
        internal static string String248 {
            get {
                return ResourceManager.GetString("String248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrive Broadcast 的本地化字符串。
        /// </summary>
        internal static string String249 {
            get {
                return ResourceManager.GetString("String249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATO 的本地化字符串。
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depart Broadcast 的本地化字符串。
        /// </summary>
        internal static string String250 {
            get {
                return ResourceManager.GetString("String250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Broadcast 的本地化字符串。
        /// </summary>
        internal static string String251 {
            get {
                return ResourceManager.GetString("String251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip station 的本地化字符串。
        /// </summary>
        internal static string String252 {
            get {
                return ResourceManager.GetString("String252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        internal static string String253 {
            get {
                return ResourceManager.GetString("String253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next station 的本地化字符串。
        /// </summary>
        internal static string String254 {
            get {
                return ResourceManager.GetString("String254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End station 的本地化字符串。
        /// </summary>
        internal static string String255 {
            get {
                return ResourceManager.GetString("String255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string String256 {
            get {
                return ResourceManager.GetString("String256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        internal static string String257 {
            get {
                return ResourceManager.GetString("String257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        internal static string String258 {
            get {
                return ResourceManager.GetString("String258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        internal static string String259 {
            get {
                return ResourceManager.GetString("String259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slip / Slide 的本地化字符串。
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temporary parking 的本地化字符串。
        /// </summary>
        internal static string String260 {
            get {
                return ResourceManager.GetString("String260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        internal static string String261 {
            get {
                return ResourceManager.GetString("String261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service delay 的本地化字符串。
        /// </summary>
        internal static string String262 {
            get {
                return ResourceManager.GetString("String262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vehicle fault 的本地化字符串。
        /// </summary>
        internal static string String263 {
            get {
                return ResourceManager.GetString("String263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evacuate passenger 的本地化字符串。
        /// </summary>
        internal static string String264 {
            get {
                return ResourceManager.GetString("String264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        internal static string String265 {
            get {
                return ResourceManager.GetString("String265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String266 {
            get {
                return ResourceManager.GetString("String266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Slip 的本地化字符串。
        /// </summary>
        internal static string String267 {
            get {
                return ResourceManager.GetString("String267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency brake 的本地化字符串。
        /// </summary>
        internal static string String268 {
            get {
                return ResourceManager.GetString("String268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traction block 的本地化字符串。
        /// </summary>
        internal static string String269 {
            get {
                return ResourceManager.GetString("String269", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency brake 的本地化字符串。
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Ready to drive 的本地化字符串。
        /// </summary>
        internal static string String270 {
            get {
                return ResourceManager.GetString("String270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String271 {
            get {
                return ResourceManager.GetString("String271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lengend PAB 的本地化字符串。
        /// </summary>
        internal static string String272 {
            get {
                return ResourceManager.GetString("String272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HVAC 的本地化字符串。
        /// </summary>
        internal static string String273 {
            get {
                return ResourceManager.GetString("String273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HVAC2 的本地化字符串。
        /// </summary>
        internal static string String274 {
            get {
                return ResourceManager.GetString("String274", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend Door 的本地化字符串。
        /// </summary>
        internal static string String275 {
            get {
                return ResourceManager.GetString("String275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Released 的本地化字符串。
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready to drive 的本地化字符串。
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interlocks 的本地化字符串。
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TE/BE reference 的本地化字符串。
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hill start 的本地化字符串。
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend 的本地化字符串。
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closed and locked 的本地化字符串。
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut-out 的本地化字符串。
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Faulty 的本地化字符串。
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency unlock 的本地化字符串。
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PEA Active 的本地化字符串。
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PEA Speeking 的本地化字符串。
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bypass overview 的本地化字符串。
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PEA Faulty 的本地化字符串。
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake OK 的本地化字符串。
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake Off 的本地化字符串。
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake Cut Out 的本地化字符串。
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake Faulty 的本地化字符串。
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status Unknown 的本地化字符串。
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency brake applied 的本地化字符串。
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency brake released 的本地化字符串。
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency brake status unknown 的本地化字符串。
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air compressor running 的本地化字符串。
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air compressor standby 的本地化字符串。
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air compressor faulty 的本地化字符串。
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parking brake applied 的本地化字符串。
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parking brake isolated 的本地化字符串。
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parking brake released 的本地化字符串。
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pantograph status unknown 的本地化字符串。
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pantograph faulty 的本地化字符串。
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pantograph down 的本地化字符串。
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pantograph up 的本地化字符串。
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line contactor open 的本地化字符串。
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event Overview 的本地化字符串。
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line contactor closed 的本地化字符串。
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line contactor not ready 的本地化字符串。
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop power supply disconnected 的本地化字符串。
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop power supply connected 的本地化字符串。
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop power supply grounded 的本地化字符串。
        /// </summary>
        internal static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCM off 的本地化字符串。
        /// </summary>
        internal static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCM cut out 的本地化字符串。
        /// </summary>
        internal static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCM faulty 的本地化字符串。
        /// </summary>
        internal static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCM in op 的本地化字符串。
        /// </summary>
        internal static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACM off 的本地化字符串。
        /// </summary>
        internal static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Car Weight 的本地化字符串。
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACM cut out 的本地化字符串。
        /// </summary>
        internal static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACM faulty 的本地化字符串。
        /// </summary>
        internal static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACM in op 的本地化字符串。
        /// </summary>
        internal static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BCM OK 的本地化字符串。
        /// </summary>
        internal static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BCM faulty 的本地化字符串。
        /// </summary>
        internal static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 central 的本地化字符串。
        /// </summary>
        internal static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cooling 的本地化字符串。
        /// </summary>
        internal static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        internal static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        internal static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ventilation 的本地化字符串。
        /// </summary>
        internal static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake test 的本地化字符串。
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaporator fan 的本地化字符串。
        /// </summary>
        internal static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condenser fan 的本地化字符串。
        /// </summary>
        internal static string String82 {
            get {
                return ResourceManager.GetString("String82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor 的本地化字符串。
        /// </summary>
        internal static string String83 {
            get {
                return ResourceManager.GetString("String83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fresh air valve 的本地化字符串。
        /// </summary>
        internal static string String84 {
            get {
                return ResourceManager.GetString("String84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return air 的本地化字符串。
        /// </summary>
        internal static string String85 {
            get {
                return ResourceManager.GetString("String85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heating HVAC 的本地化字符串。
        /// </summary>
        internal static string String86 {
            get {
                return ResourceManager.GetString("String86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heating Pass 的本地化字符串。
        /// </summary>
        internal static string String87 {
            get {
                return ResourceManager.GetString("String87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inside temp ℃ 的本地化字符串。
        /// </summary>
        internal static string String88 {
            get {
                return ResourceManager.GetString("String88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set temp ℃ 的本地化字符串。
        /// </summary>
        internal static string String89 {
            get {
                return ResourceManager.GetString("String89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIS test 的本地化字符串。
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control mode 的本地化字符串。
        /// </summary>
        internal static string String90 {
            get {
                return ResourceManager.GetString("String90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Working mode 的本地化字符串。
        /// </summary>
        internal static string String91 {
            get {
                return ResourceManager.GetString("String91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit on 的本地化字符串。
        /// </summary>
        internal static string String92 {
            get {
                return ResourceManager.GetString("String92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit off 的本地化字符串。
        /// </summary>
        internal static string String93 {
            get {
                return ResourceManager.GetString("String93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit faulty 的本地化字符串。
        /// </summary>
        internal static string String94 {
            get {
                return ResourceManager.GetString("String94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fresh air 1/1 的本地化字符串。
        /// </summary>
        internal static string String95 {
            get {
                return ResourceManager.GetString("String95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fresh air 2/3 的本地化字符串。
        /// </summary>
        internal static string String96 {
            get {
                return ResourceManager.GetString("String96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fresh air 1/3 的本地化字符串。
        /// </summary>
        internal static string String97 {
            get {
                return ResourceManager.GetString("String97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fresh air off 的本地化字符串。
        /// </summary>
        internal static string String98 {
            get {
                return ResourceManager.GetString("String98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fresh air faulty 的本地化字符串。
        /// </summary>
        internal static string String99 {
            get {
                return ResourceManager.GetString("String99", resourceCulture);
            }
        }
    }
}
