using System.Windows;

namespace Subway.XiaMenLine1.Interface.Model
{
    public interface IDoor : IViewModel
    {
        Visibility Car1Door10StatusVisibility { get; }
        Visibility Car1Door1StatusVisibility { get; }
        Visibility Car1Door2StatusVisibility { get; }
        Visibility Car1Door3StatusVisibility { get; }
        Visibility Car1Door4StatusVisibility { get; }
        Visibility Car1Door5StatusVisibility { get; }
        Visibility Car1Door6StatusVisibility { get; }
        Visibility Car1Door7StatusVisibility { get; }
        Visibility Car1Door8StatusVisibility { get; }
        Visibility Car1Door9StatusVisibility { get; }
        Visibility Car2Door10StatusVisibility { get; }
        Visibility Car2Door1StatusVisibility { get; }
        Visibility Car2Door2StatusVisibility { get; }
        Visibility Car2Door3StatusVisibility { get; }
        Visibility Car2Door4StatusVisibility { get; }
        Visibility Car2Door5StatusVisibility { get; }
        Visibility Car2Door6StatusVisibility { get; }
        Visibility Car2Door7StatusVisibility { get; }
        Visibility Car2Door8StatusVisibility { get; }
        Visibility Car2Door9StatusVisibility { get; }
        Visibility Car3Door10StatusVisibility { get; }
        Visibility Car3Door1StatusVisibility { get; }
        Visibility Car3Door2StatusVisibility { get; }
        Visibility Car3Door3StatusVisibility { get; }
        Visibility Car3Door4StatusVisibility { get; }
        Visibility Car3Door5StatusVisibility { get; }
        Visibility Car3Door6StatusVisibility { get; }
        Visibility Car3Door7StatusVisibility { get; }
        Visibility Car3Door8StatusVisibility { get; }
        Visibility Car3Door9StatusVisibility { get; }
        Visibility Car4Door10StatusVisibility { get; }
        Visibility Car4Door1StatusVisibility { get; }
        Visibility Car4Door2StatusVisibility { get; }
        Visibility Car4Door3StatusVisibility { get; }
        Visibility Car4Door4StatusVisibility { get; }
        Visibility Car4Door5StatusVisibility { get; }
        Visibility Car4Door6StatusVisibility { get; }
        Visibility Car4Door7StatusVisibility { get; }
        Visibility Car4Door8StatusVisibility { get; }
        Visibility Car4Door9StatusVisibility { get; }
        Visibility Car5Door10StatusVisibility { get; }
        Visibility Car5Door1StatusVisibility { get; }
        Visibility Car5Door2StatusVisibility { get; }
        Visibility Car5Door3StatusVisibility { get; }
        Visibility Car5Door4StatusVisibility { get; }
        Visibility Car5Door5StatusVisibility { get; }
        Visibility Car5Door6StatusVisibility { get; }
        Visibility Car5Door7StatusVisibility { get; }
        Visibility Car5Door8StatusVisibility { get; }
        Visibility Car5Door9StatusVisibility { get; }
        Visibility Car6Door10StatusVisibility { get; }
        Visibility Car6Door1StatusVisibility { get; }
        Visibility Car6Door2StatusVisibility { get; }
        Visibility Car6Door3StatusVisibility { get; }
        Visibility Car6Door4StatusVisibility { get; }
        Visibility Car6Door5StatusVisibility { get; }
        Visibility Car6Door6StatusVisibility { get; }
        Visibility Car6Door7StatusVisibility { get; }
        Visibility Car6Door8StatusVisibility { get; }
        Visibility Car6Door9StatusVisibility { get; }
        Enum.DoorStatus Car1Door9Status { get; }
        Enum.DoorStatus Car1Door10Status { get; }
        Enum.DoorStatus Car2Door9Status { get; }
        Enum.DoorStatus Car2Door10Status { get; }
        Enum.DoorStatus Car3Door9Status { get; }
        Enum.DoorStatus Car3Door10Status { get; }
        Enum.DoorStatus Car4Door9Status { get; }
        Enum.DoorStatus Car4Door10Status { get; }
        Enum.DoorStatus Car5Door9Status { get; }
        Enum.DoorStatus Car5Door10Status { get; }
        Enum.DoorStatus Car6Door9Status { get; }
        Enum.DoorStatus Car6Door10Status { get; }
        Enum.DoorStatus Car1Door1Status { get; }
        Enum.DoorStatus Car1Door2Status { get; }
        Enum.DoorStatus Car1Door3Status { get; }
        Enum.DoorStatus Car1Door4Status { get; }
        Enum.DoorStatus Car1Door5Status { get; }
        Enum.DoorStatus Car1Door6Status { get; }
        Enum.DoorStatus Car1Door7Status { get; }
        Enum.DoorStatus Car1Door8Status { get; }
        Enum.DoorStatus Car2Door1Status { get; }
        Enum.DoorStatus Car2Door2Status { get; }
        Enum.DoorStatus Car2Door3Status { get; }
        Enum.DoorStatus Car2Door4Status { get; }
        Enum.DoorStatus Car2Door5Status { get; }
        Enum.DoorStatus Car2Door6Status { get; }
        Enum.DoorStatus Car2Door7Status { get; }
        Enum.DoorStatus Car2Door8Status { get; }
        Enum.DoorStatus Car3Door1Status { get; }
        Enum.DoorStatus Car3Door2Status { get; }
        Enum.DoorStatus Car3Door3Status { get; }
        Enum.DoorStatus Car3Door4Status { get; }
        Enum.DoorStatus Car3Door5Status { get; }
        Enum.DoorStatus Car3Door6Status { get; }
        Enum.DoorStatus Car3Door7Status { get; }
        Enum.DoorStatus Car3Door8Status { get; }
        Enum.DoorStatus Car4Door1Status { get; }
        Enum.DoorStatus Car4Door2Status { get; }
        Enum.DoorStatus Car4Door3Status { get; }
        Enum.DoorStatus Car4Door4Status { get; }
        Enum.DoorStatus Car4Door5Status { get; }
        Enum.DoorStatus Car4Door6Status { get; }
        Enum.DoorStatus Car4Door7Status { get; }
        Enum.DoorStatus Car4Door8Status { get; }
        Enum.DoorStatus Car5Door1Status { get; }
        Enum.DoorStatus Car5Door2Status { get; }
        Enum.DoorStatus Car5Door3Status { get; }
        Enum.DoorStatus Car5Door4Status { get; }
        Enum.DoorStatus Car5Door5Status { get; }
        Enum.DoorStatus Car5Door6Status { get; }
        Enum.DoorStatus Car5Door7Status { get; }
        Enum.DoorStatus Car5Door8Status { get; }
        Enum.DoorStatus Car6Door1Status { get; }
        Enum.DoorStatus Car6Door2Status { get; }
        Enum.DoorStatus Car6Door3Status { get; }
        Enum.DoorStatus Car6Door4Status { get; }
        Enum.DoorStatus Car6Door5Status { get; }
        Enum.DoorStatus Car6Door6Status { get; }
        Enum.DoorStatus Car6Door7Status { get; }
        Enum.DoorStatus Car6Door8Status { get; }

    }
}