//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.TCMS.Turkmenistan.Resources.Keys {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InBoolKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InBoolKeys() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.TCMS.Turkmenistan.Resources.Keys.InBoolKeys", typeof(InBoolKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 F1按键按下 的本地化字符串。
        /// </summary>
        internal static string InBF1按键按下 {
            get {
                return ResourceManager.GetString("InBF1按键按下", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F2按键按下 的本地化字符串。
        /// </summary>
        internal static string InBF2按键按下 {
            get {
                return ResourceManager.GetString("InBF2按键按下", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F3按键按下 的本地化字符串。
        /// </summary>
        internal static string InBF3按键按下 {
            get {
                return ResourceManager.GetString("InBF3按键按下", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F4按键按下 的本地化字符串。
        /// </summary>
        internal static string InBF4按键按下 {
            get {
                return ResourceManager.GetString("InBF4按键按下", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F5按键按下 的本地化字符串。
        /// </summary>
        internal static string InBF5按键按下 {
            get {
                return ResourceManager.GetString("InBF5按键按下", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 他车工作正常 的本地化字符串。
        /// </summary>
        internal static string InB他车工作正常 {
            get {
                return ResourceManager.GetString("InB他车工作正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制动工况 的本地化字符串。
        /// </summary>
        internal static string InB制动工况 {
            get {
                return ResourceManager.GetString("InB制动工况", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载后界面切换 的本地化字符串。
        /// </summary>
        internal static string InB加载后界面切换 {
            get {
                return ResourceManager.GetString("InB加载后界面切换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 惰转工况 的本地化字符串。
        /// </summary>
        internal static string InB惰转工况 {
            get {
                return ResourceManager.GetString("InB惰转工况", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本车工作正常 的本地化字符串。
        /// </summary>
        internal static string InB本车工作正常 {
            get {
                return ResourceManager.GetString("InB本车工作正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机车惰转 的本地化字符串。
        /// </summary>
        internal static string InB机车惰转 {
            get {
                return ResourceManager.GetString("InB机车惰转", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机车牵引 的本地化字符串。
        /// </summary>
        internal static string InB机车牵引 {
            get {
                return ResourceManager.GetString("InB机车牵引", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机车电制 的本地化字符串。
        /// </summary>
        internal static string InB机车电制 {
            get {
                return ResourceManager.GetString("InB机车电制", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--0位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机0位 {
            get {
                return ResourceManager.GetString("InB柴油机0位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--10位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机10位 {
            get {
                return ResourceManager.GetString("InB柴油机10位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--11位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机11位 {
            get {
                return ResourceManager.GetString("InB柴油机11位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--12位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机12位 {
            get {
                return ResourceManager.GetString("InB柴油机12位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--13位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机13位 {
            get {
                return ResourceManager.GetString("InB柴油机13位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--14位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机14位 {
            get {
                return ResourceManager.GetString("InB柴油机14位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--15位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机15位 {
            get {
                return ResourceManager.GetString("InB柴油机15位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--16位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机16位 {
            get {
                return ResourceManager.GetString("InB柴油机16位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--1位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机1位 {
            get {
                return ResourceManager.GetString("InB柴油机1位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--2位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机2位 {
            get {
                return ResourceManager.GetString("InB柴油机2位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--3位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机3位 {
            get {
                return ResourceManager.GetString("InB柴油机3位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--4位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机4位 {
            get {
                return ResourceManager.GetString("InB柴油机4位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--5位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机5位 {
            get {
                return ResourceManager.GetString("InB柴油机5位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--6位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机6位 {
            get {
                return ResourceManager.GetString("InB柴油机6位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--7位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机7位 {
            get {
                return ResourceManager.GetString("InB柴油机7位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--8位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机8位 {
            get {
                return ResourceManager.GetString("InB柴油机8位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柴油机--9位 的本地化字符串。
        /// </summary>
        internal static string InB柴油机9位 {
            get {
                return ResourceManager.GetString("InB柴油机9位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 牵引工况 的本地化字符串。
        /// </summary>
        internal static string InB牵引工况 {
            get {
                return ResourceManager.GetString("InB牵引工况", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自负荷工况 的本地化字符串。
        /// </summary>
        internal static string InB自负荷工况 {
            get {
                return ResourceManager.GetString("InB自负荷工况", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重联屏故障黑屏 的本地化字符串。
        /// </summary>
        internal static string InB重联屏故障黑屏 {
            get {
                return ResourceManager.GetString("InB重联屏故障黑屏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重阀位置1 的本地化字符串。
        /// </summary>
        internal static string InB重阀位置1 {
            get {
                return ResourceManager.GetString("InB重阀位置1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重阀位置2 的本地化字符串。
        /// </summary>
        internal static string InB重阀位置2 {
            get {
                return ResourceManager.GetString("InB重阀位置2", resourceCulture);
            }
        }
    }
}
