//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Motor.HMI.CRH3C380B.Resource.Images {
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class CommonImages {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonImages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Motor.HMI.CRH3C380B.Resource.Images.CommonImages", typeof(CommonImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap che {
            get {
                object obj = ResourceManager.GetObject("che", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap doubleDoor {
            get {
                object obj = ResourceManager.GetObject("doubleDoor", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap EmergencyModelGuide {
            get {
                object obj = ResourceManager.GetObject("EmergencyModelGuide", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap sijishi {
            get {
                object obj = ResourceManager.GetObject("sijishi", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap StateUnkown {
            get {
                object obj = ResourceManager.GetObject("StateUnkown", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap welcom {
            get {
                object obj = ResourceManager.GetObject("welcom", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap zhou {
            get {
                object obj = ResourceManager.GetObject("zhou", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 升弓_0 {
            get {
                object obj = ResourceManager.GetObject("升弓_0", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 升弓_1 {
            get {
                object obj = ResourceManager.GetObject("升弓_1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 开关牵引16_0 {
            get {
                object obj = ResourceManager.GetObject("开关牵引16_0", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 开关牵引16_1 {
            get {
                object obj = ResourceManager.GetObject("开关牵引16_1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 开关牵引8_0 {
            get {
                object obj = ResourceManager.GetObject("开关牵引8_0", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 开关牵引8_1 {
            get {
                object obj = ResourceManager.GetObject("开关牵引8_1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 车灯a {
            get {
                object obj = ResourceManager.GetObject("车灯a", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 车灯b {
            get {
                object obj = ResourceManager.GetObject("车灯b", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 车灯c {
            get {
                object obj = ResourceManager.GetObject("车灯c", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 车灯d {
            get {
                object obj = ResourceManager.GetObject("车灯d", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 车灯e {
            get {
                object obj = ResourceManager.GetObject("车灯e", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 车灯f {
            get {
                object obj = ResourceManager.GetObject("车灯f", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 降弓_0 {
            get {
                object obj = ResourceManager.GetObject("降弓_0", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 降弓_1 {
            get {
                object obj = ResourceManager.GetObject("降弓_1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
