//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motor.ATP.Domain.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DriverInterfaceKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DriverInterfaceKeys() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motor.ATP.Domain.Model.Resources.DriverInterfaceKeys", typeof(DriverInterfaceKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Root 的本地化字符串。
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-其它 的本地化字符串。
        /// </summary>
        public static string Root_其它 {
            get {
                return ResourceManager.GetString("Root_其它", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-其它-制动测试 的本地化字符串。
        /// </summary>
        public static string Root_其它_制动测试 {
            get {
                return ResourceManager.GetString("Root_其它_制动测试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-其它-设置亮度 的本地化字符串。
        /// </summary>
        public static string Root_其它_设置亮度 {
            get {
                return ResourceManager.GetString("Root_其它_设置亮度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-其它-设置音量 的本地化字符串。
        /// </summary>
        public static string Root_其它_设置音量 {
            get {
                return ResourceManager.GetString("Root_其它_设置音量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-数据 的本地化字符串。
        /// </summary>
        public static string Root_数据 {
            get {
                return ResourceManager.GetString("Root_数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-数据-RBC数据 的本地化字符串。
        /// </summary>
        public static string Root_数据_RBC数据 {
            get {
                return ResourceManager.GetString("Root_数据_RBC数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-数据-列车数据 的本地化字符串。
        /// </summary>
        public static string Root_数据_列车数据 {
            get {
                return ResourceManager.GetString("Root_数据_列车数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-数据-司机号 的本地化字符串。
        /// </summary>
        public static string Root_数据_司机号 {
            get {
                return ResourceManager.GetString("Root_数据_司机号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-数据-日期时间 的本地化字符串。
        /// </summary>
        public static string Root_数据_日期时间 {
            get {
                return ResourceManager.GetString("Root_数据_日期时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-数据-车次号 的本地化字符串。
        /// </summary>
        public static string Root_数据_车次号 {
            get {
                return ResourceManager.GetString("Root_数据_车次号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-模式 的本地化字符串。
        /// </summary>
        public static string Root_模式 {
            get {
                return ResourceManager.GetString("Root_模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-模式确认取消机信 的本地化字符串。
        /// </summary>
        public static string Root_模式确认取消机信 {
            get {
                return ResourceManager.GetString("Root_模式确认取消机信", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-模式确认取消目视 的本地化字符串。
        /// </summary>
        public static string Root_模式确认取消目视 {
            get {
                return ResourceManager.GetString("Root_模式确认取消目视", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-模式确认取消调车 的本地化字符串。
        /// </summary>
        public static string Root_模式确认取消调车 {
            get {
                return ResourceManager.GetString("Root_模式确认取消调车", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-确认删除取消 的本地化字符串。
        /// </summary>
        public static string Root_确认删除取消 {
            get {
                return ResourceManager.GetString("Root_确认删除取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-确认取消列车数据 的本地化字符串。
        /// </summary>
        public static string Root_确认取消列车数据 {
            get {
                return ResourceManager.GetString("Root_确认取消列车数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-确认取消启动 的本地化字符串。
        /// </summary>
        public static string Root_确认取消启动 {
            get {
                return ResourceManager.GetString("Root_确认取消启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-确认取消无弹出框 的本地化字符串。
        /// </summary>
        public static string Root_确认取消无弹出框 {
            get {
                return ResourceManager.GetString("Root_确认取消无弹出框", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-确认取消有弹出框 的本地化字符串。
        /// </summary>
        public static string Root_确认取消有弹出框 {
            get {
                return ResourceManager.GetString("Root_确认取消有弹出框", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-确认取消缓解制动 的本地化字符串。
        /// </summary>
        public static string Root_确认取消缓解制动 {
            get {
                return ResourceManager.GetString("Root_确认取消缓解制动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-确认取消载频 的本地化字符串。
        /// </summary>
        public static string Root_确认取消载频 {
            get {
                return ResourceManager.GetString("Root_确认取消载频", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-确认无弹出框 的本地化字符串。
        /// </summary>
        public static string Root_确认无弹出框 {
            get {
                return ResourceManager.GetString("Root_确认无弹出框", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-确认有弹出框 的本地化字符串。
        /// </summary>
        public static string Root_确认有弹出框 {
            get {
                return ResourceManager.GetString("Root_确认有弹出框", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-等级 的本地化字符串。
        /// </summary>
        public static string Root_等级 {
            get {
                return ResourceManager.GetString("Root_等级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-等级确认取消CTCS2 的本地化字符串。
        /// </summary>
        public static string Root_等级确认取消CTCS2 {
            get {
                return ResourceManager.GetString("Root_等级确认取消CTCS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-等级确认取消CTCS3 的本地化字符串。
        /// </summary>
        public static string Root_等级确认取消CTCS3 {
            get {
                return ResourceManager.GetString("Root_等级确认取消CTCS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-载频 的本地化字符串。
        /// </summary>
        public static string Root_载频 {
            get {
                return ResourceManager.GetString("Root_载频", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-载频确认取消上行 的本地化字符串。
        /// </summary>
        public static string Root_载频确认取消上行 {
            get {
                return ResourceManager.GetString("Root_载频确认取消上行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root-载频确认取消下行 的本地化字符串。
        /// </summary>
        public static string Root_载频确认取消下行 {
            get {
                return ResourceManager.GetString("Root_载频确认取消下行", resourceCulture);
            }
        }
    }
}
