//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.TCMS.HXD3D.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InbKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InbKeys() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.TCMS.HXD3D.Resource.InbKeys", typeof(InbKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/BCU红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_BCU红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_BCU红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/BCU黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_BCU黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_BCU黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI1红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI1红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI1红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI1黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI1黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI1黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI2红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI2红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI2红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI2黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI2黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI2黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI3红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI3红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI3红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI3黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI3黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI3黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI4红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI4红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI4红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI4黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI4黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI4黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI5红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI5红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI5红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI5黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI5黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI5黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI6红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI6红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI6红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CI6黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CI6黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CI6黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CMD红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CMD红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CMD红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/CMD黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_CMD黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_CMD黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/COV1红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_COV1红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_COV1红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/COV1黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_COV1黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_COV1黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/COV2红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_COV2红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_COV2红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/COV2黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_COV2黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_COV2黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/INV1红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_INV1红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_INV1红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/INV1黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_INV1黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_INV1黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/INV2红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_INV2红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_INV2红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/INV2黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_INV2黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_INV2黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/LG1红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_LG1红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_LG1红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/LG1黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_LG1黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_LG1黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/LG2红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_LG2红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_LG2红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/LG2黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_LG2黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_LG2黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/MPU-MASTER红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_MPU_MASTER红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_MPU_MASTER红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/MPU-MASTER黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_MPU_MASTER黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_MPU_MASTER黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/MPU-SLAVE红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_MPU_SLAVE红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_MPU_SLAVE红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/MPU-SLAVE黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_MPU_SLAVE黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_MPU_SLAVE黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/PSU1     红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_PSU1红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_PSU1红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/PSU1     黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_PSU1黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_PSU1黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/PSU2红 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_PSU2红 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_PSU2红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/PSU2黄 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_PSU2黄 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_PSU2黄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/1049 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_1049 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/2804 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_2804 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_2804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/436 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_436 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_436", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/437 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_437 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/451 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_451 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/452 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_452 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_452", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/466 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_466 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_466", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/468 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_468 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_468", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/469 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_469 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_469", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/472 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_472 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_472", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/473 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_473 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_473", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/474 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_474 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_474", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/475 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_475 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_475", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/477 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_477 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_477", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/478 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_478 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_478", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/487 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_487 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_487", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/542 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_542 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_542", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/593 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_593 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_593", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/693 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_693 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_693", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/725 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_725 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_725", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/810 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_810 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_810", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/820 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_820 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_820", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/837 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_837 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_837", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/838 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_838 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_838", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/842 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_842 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_842", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/847 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_847 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_847", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/887 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_887 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_887", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/888 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_888 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_888", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/889 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_889 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_889", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/890 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_890 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_890", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/981 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_981 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_981", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/986 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_986 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_986", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/988 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_988 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_988", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/DI148 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_DI148 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_DI148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/DI149 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_DI149 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_DI149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/DI151 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_DI151 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_DI151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/DO012 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_DO012 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_DO012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/OTRKOUT1 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_OTRKOUT1 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_OTRKOUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/OTRKOUT2 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_OTRKOUT2 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_OTRKOUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX1/空白 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX1_空白 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX1_空白", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/1021 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_1021 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/1025 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_1025 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/1054 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_1054 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_1054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/1055 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_1055 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/355/453 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_355_453 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_355_453", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/445 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_445 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_445", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/446 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_446 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_446", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/462 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_462 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/491 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_491 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_491", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/781 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_781 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_781", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/782 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_782 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_782", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/783 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_783 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_783", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/784 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_784 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_784", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/829 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_829 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_829", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/830 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_830 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_830", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/831 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_831 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_831", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/832 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_832 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_832", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/838 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_838 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_838", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/866 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_866 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/867 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_867 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_867", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/963 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_963 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_963", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/964 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_964 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_964", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/965 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_965 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_965", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/CABCHG 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_CABCHG {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_CABCHG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/DISPCHG 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_DISPCHG {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_DISPCHG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/TRANCHG 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_TRANCHG {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_TRANCHG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/VCBOFF 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_VCBOFF {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_VCBOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/X09/461 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_X09_461 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_X09_461", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/X10/462 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_X10_462 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_X10_462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/X12/463 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_X12_463 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_X12_463", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/X13/464 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_X13_464 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_X13_464", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/AUX2/X14/465 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_AUX2_X14_465 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_AUX2_X14_465", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/1009 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_1009 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/1010 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_1010 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/1019 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_1019 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/1020 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_1020 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/1022 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_1022 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/1026 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_1026 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/1067 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_1067 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_1067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/401 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_401 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/402 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_402 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/403 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_403 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/404 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_404 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/407 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_407 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/408 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_408 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/409 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_409 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/410 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_410 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/411 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_411 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/412 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_412 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/413 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_413 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/414 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_414 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/417 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_417 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/418 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_418 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/419 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_419 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/420 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_420 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/427 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_427 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_427", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/428 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_428 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_428", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/429 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_429 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/430 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_430 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/431 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_431 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/432 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_432 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/434 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_434 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/435 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_435 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_435", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/441 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_441 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_441", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/483 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_483 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_483", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/533 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_533 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_533", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/538 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_538 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_538", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/583 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_583 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_583", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/584 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_584 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_584", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/585 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_585 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_585", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/590 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_590 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_590", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/591 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_591 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_591", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/601 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_601 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/602 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_602 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/633 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_633 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_633", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/638 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_638 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_638", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/643 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_643 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_643", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/644 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_644 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_644", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/662 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_662 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_662", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/663 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_663 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_663", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/664 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_664 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_664", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/681 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_681 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_681", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/683 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_683 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_683", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/684 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_684 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_684", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/685 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_685 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_685", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/690 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_690 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_690", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/699 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_699 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_699", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/803 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_803 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/821 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_821 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_821", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/822 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_822 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_822", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/824 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_824 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_824", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/825 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_825 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_825", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/828 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_828 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_828", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/835 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_835 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_835", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/840 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_840 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_840", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/841 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_841 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_841", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/845 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_845 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_845", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/867 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_867 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_867", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/868 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_868 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_868", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/962 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_962 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_962", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/982 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_982 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_982", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/983 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_983 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_983", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/CNDET7 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_CNDET7 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_CNDET7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI1/CNDET8 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI1_CNDET8 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI1_CNDET8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/1804 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_1804 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_1804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/423 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_423 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/424 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_424 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/448 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_448 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_448", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/449 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_449 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_449", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/479 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_479 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_479", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/480 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_480 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/481 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_481 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_481", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/482 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_482 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_482", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/495 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_495 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_495", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/496 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_496 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_496", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/497 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_497 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_497", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/498 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_498 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_498", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/499 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_499 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_499", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/501 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_501 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/502 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_502 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/503 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_503 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/504 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_504 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/506 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_506 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/507 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_507 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/508 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_508 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/514 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_514 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/515 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_515 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/516 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_516 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/517 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_517 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/518 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_518 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_518", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/519 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_519 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/520 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_520 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/521 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_521 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/522 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_522 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/523 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_523 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_523", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/524 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_524 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_524", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/531 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_531 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/549 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_549 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_549", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/601 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_601 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/602 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_602 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/603 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_603 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/604 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_604 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/606 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_606 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/607 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_607 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/608 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_608 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/614 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_614 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/615 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_615 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_615", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/616 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_616 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_616", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/617 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_617 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_617", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/618 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_618 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_618", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/619 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_619 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_619", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/621 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_621 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_621", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/622 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_622 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_622", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/624 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_624 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_624", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/631 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_631 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_631", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/708 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_708 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/709 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_709 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_709", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/710 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_710 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/712 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_712 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_712", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/803 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_803 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/804 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_804 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/806 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_806 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_806", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/811 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_811 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_811", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/812 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_812 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_812", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/823 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_823 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_823", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/826 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_826 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_826", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/827 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_827 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_827", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/842 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_842 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_842", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/843 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_843 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_843", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/844 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_844 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_844", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/851 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_851 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_851", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/852 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_852 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_852", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/866 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_866 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/DI095 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_DI095 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_DI095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/DIG1 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_DIG1 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_DIG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程数据/网络控制/信号信息/DI2/DIG2 的本地化字符串。
        /// </summary>
        internal static string 过程数据_网络控制_信号信息_DI2_DIG2 {
            get {
                return ResourceManager.GetString("过程数据_网络控制_信号信息_DI2_DIG2", resourceCulture);
            }
        }
    }
}
