//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightRail.HMI.SZLHLF.Resources.Keys {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InBoolKey {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InBoolKey() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightRail.HMI.SZLHLF.Resources.Keys.InBoolKey", typeof(InBoolKey).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MC1侧司机室激活 的本地化字符串。
        /// </summary>
        internal static string MC1侧司机室激活 {
            get {
                return ResourceManager.GetString("MC1侧司机室激活", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MC2侧司机室激活 的本地化字符串。
        /// </summary>
        internal static string MC2侧司机室激活 {
            get {
                return ResourceManager.GetString("MC2侧司机室激活", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工况_制动 的本地化字符串。
        /// </summary>
        internal static string 工况_制动 {
            get {
                return ResourceManager.GetString("工况_制动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工况_快速制动 的本地化字符串。
        /// </summary>
        internal static string 工况_快速制动 {
            get {
                return ResourceManager.GetString("工况_快速制动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工况_惰性 的本地化字符串。
        /// </summary>
        internal static string 工况_惰性 {
            get {
                return ResourceManager.GetString("工况_惰性", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工况_牵引 的本地化字符串。
        /// </summary>
        internal static string 工况_牵引 {
            get {
                return ResourceManager.GetString("工况_牵引", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工况_紧急制动 的本地化字符串。
        /// </summary>
        internal static string 工况_紧急制动 {
            get {
                return ResourceManager.GetString("工况_紧急制动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工况_紧急牵引 的本地化字符串。
        /// </summary>
        internal static string 工况_紧急牵引 {
            get {
                return ResourceManager.GetString("工况_紧急牵引", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向前 的本地化字符串。
        /// </summary>
        internal static string 方向前 {
            get {
                return ResourceManager.GetString("方向前", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向后 的本地化字符串。
        /// </summary>
        internal static string 方向后 {
            get {
                return ResourceManager.GetString("方向后", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向零 的本地化字符串。
        /// </summary>
        internal static string 方向零 {
            get {
                return ResourceManager.GetString("方向零", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模式_洗车模式 的本地化字符串。
        /// </summary>
        internal static string 模式_洗车模式 {
            get {
                return ResourceManager.GetString("模式_洗车模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1火警报出 的本地化字符串。
        /// </summary>
        internal static string 车1火警报出 {
            get {
                return ResourceManager.GetString("车1火警报出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1空调模式_制冷模式 的本地化字符串。
        /// </summary>
        internal static string 车1空调模式_制冷模式 {
            get {
                return ResourceManager.GetString("车1空调模式_制冷模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1空调模式_制热模式 的本地化字符串。
        /// </summary>
        internal static string 车1空调模式_制热模式 {
            get {
                return ResourceManager.GetString("车1空调模式_制热模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1空调模式_通风模式 的本地化字符串。
        /// </summary>
        internal static string 车1空调模式_通风模式 {
            get {
                return ResourceManager.GetString("车1空调模式_通风模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1空调模式_除湿模式 的本地化字符串。
        /// </summary>
        internal static string 车1空调模式_除湿模式 {
            get {
                return ResourceManager.GetString("车1空调模式_除湿模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1辅助电源严重故障 的本地化字符串。
        /// </summary>
        internal static string 车1辅助电源严重故障 {
            get {
                return ResourceManager.GetString("车1辅助电源严重故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1辅助电源未运行 的本地化字符串。
        /// </summary>
        internal static string 车1辅助电源未运行 {
            get {
                return ResourceManager.GetString("车1辅助电源未运行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1辅助电源次要故障 的本地化字符串。
        /// </summary>
        internal static string 车1辅助电源次要故障 {
            get {
                return ResourceManager.GetString("车1辅助电源次要故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1辅助电源正常 的本地化字符串。
        /// </summary>
        internal static string 车1辅助电源正常 {
            get {
                return ResourceManager.GetString("车1辅助电源正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2受电弓升起 的本地化字符串。
        /// </summary>
        internal static string 车2受电弓升起 {
            get {
                return ResourceManager.GetString("车2受电弓升起", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2受电弓降下 的本地化字符串。
        /// </summary>
        internal static string 车2受电弓降下 {
            get {
                return ResourceManager.GetString("车2受电弓降下", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2火警报出 的本地化字符串。
        /// </summary>
        internal static string 车2火警报出 {
            get {
                return ResourceManager.GetString("车2火警报出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2空调模式_制冷模式 的本地化字符串。
        /// </summary>
        internal static string 车2空调模式_制冷模式 {
            get {
                return ResourceManager.GetString("车2空调模式_制冷模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2空调模式_制热模式 的本地化字符串。
        /// </summary>
        internal static string 车2空调模式_制热模式 {
            get {
                return ResourceManager.GetString("车2空调模式_制热模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2空调模式_通风模式 的本地化字符串。
        /// </summary>
        internal static string 车2空调模式_通风模式 {
            get {
                return ResourceManager.GetString("车2空调模式_通风模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2空调模式_除湿模式 的本地化字符串。
        /// </summary>
        internal static string 车2空调模式_除湿模式 {
            get {
                return ResourceManager.GetString("车2空调模式_除湿模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2高速断路器分 的本地化字符串。
        /// </summary>
        internal static string 车2高速断路器分 {
            get {
                return ResourceManager.GetString("车2高速断路器分", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2高速断路器合 的本地化字符串。
        /// </summary>
        internal static string 车2高速断路器合 {
            get {
                return ResourceManager.GetString("车2高速断路器合", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3火警报出 的本地化字符串。
        /// </summary>
        internal static string 车3火警报出 {
            get {
                return ResourceManager.GetString("车3火警报出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3空调模式_制冷模式 的本地化字符串。
        /// </summary>
        internal static string 车3空调模式_制冷模式 {
            get {
                return ResourceManager.GetString("车3空调模式_制冷模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3空调模式_制热模式 的本地化字符串。
        /// </summary>
        internal static string 车3空调模式_制热模式 {
            get {
                return ResourceManager.GetString("车3空调模式_制热模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3空调模式_通风模式 的本地化字符串。
        /// </summary>
        internal static string 车3空调模式_通风模式 {
            get {
                return ResourceManager.GetString("车3空调模式_通风模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3空调模式_除湿模式 的本地化字符串。
        /// </summary>
        internal static string 车3空调模式_除湿模式 {
            get {
                return ResourceManager.GetString("车3空调模式_除湿模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4充电机未运行 的本地化字符串。
        /// </summary>
        internal static string 车4充电机未运行 {
            get {
                return ResourceManager.GetString("车4充电机未运行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4充电机运行 的本地化字符串。
        /// </summary>
        internal static string 车4充电机运行 {
            get {
                return ResourceManager.GetString("车4充电机运行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4火警报出 的本地化字符串。
        /// </summary>
        internal static string 车4火警报出 {
            get {
                return ResourceManager.GetString("车4火警报出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4空调模式_制冷模式 的本地化字符串。
        /// </summary>
        internal static string 车4空调模式_制冷模式 {
            get {
                return ResourceManager.GetString("车4空调模式_制冷模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4空调模式_制热模式 的本地化字符串。
        /// </summary>
        internal static string 车4空调模式_制热模式 {
            get {
                return ResourceManager.GetString("车4空调模式_制热模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4空调模式_通风模式 的本地化字符串。
        /// </summary>
        internal static string 车4空调模式_通风模式 {
            get {
                return ResourceManager.GetString("车4空调模式_通风模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4空调模式_除湿模式 的本地化字符串。
        /// </summary>
        internal static string 车4空调模式_除湿模式 {
            get {
                return ResourceManager.GetString("车4空调模式_除湿模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转向架裙板故障 的本地化字符串。
        /// </summary>
        internal static string 转向架裙板故障 {
            get {
                return ResourceManager.GetString("转向架裙板故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转向灯右 的本地化字符串。
        /// </summary>
        internal static string 转向灯右 {
            get {
                return ResourceManager.GetString("转向灯右", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转向灯左 的本地化字符串。
        /// </summary>
        internal static string 转向灯左 {
            get {
                return ResourceManager.GetString("转向灯左", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑屏 的本地化字符串。
        /// </summary>
        internal static string 黑屏 {
            get {
                return ResourceManager.GetString("黑屏", resourceCulture);
            }
        }
    }
}
