//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tram.CBTC.DataAdapter.Resource.Keys {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfKeys() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tram.CBTC.DataAdapter.Resource.Keys.InfKeys", typeof(InfKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ATP保护控制 的本地化字符串。
        /// </summary>
        internal static string ATP保护控制 {
            get {
                return ResourceManager.GetString("ATP保护控制", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATP启动状态 的本地化字符串。
        /// </summary>
        internal static string ATP启动状态 {
            get {
                return ResourceManager.GetString("ATP启动状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATP当前限速 的本地化字符串。
        /// </summary>
        internal static string ATP当前限速 {
            get {
                return ResourceManager.GetString("ATP当前限速", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATP状态 的本地化字符串。
        /// </summary>
        internal static string ATP状态 {
            get {
                return ResourceManager.GetString("ATP状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CBTC连接状态 的本地化字符串。
        /// </summary>
        internal static string CBTC连接状态 {
            get {
                return ResourceManager.GetString("CBTC连接状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CP状态 的本地化字符串。
        /// </summary>
        internal static string CP状态 {
            get {
                return ResourceManager.GetString("CP状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ELS状态 的本地化字符串。
        /// </summary>
        internal static string ELS状态 {
            get {
                return ResourceManager.GetString("ELS状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS工作状态 的本地化字符串。
        /// </summary>
        internal static string GPS工作状态 {
            get {
                return ResourceManager.GetString("GPS工作状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS状态 的本地化字符串。
        /// </summary>
        internal static string GPS状态 {
            get {
                return ResourceManager.GetString("GPS状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NTC状态 的本地化字符串。
        /// </summary>
        internal static string NTC状态 {
            get {
                return ResourceManager.GetString("NTC状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RR状态 的本地化字符串。
        /// </summary>
        internal static string RR状态 {
            get {
                return ResourceManager.GetString("RR状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STA状态 的本地化字符串。
        /// </summary>
        internal static string STA状态 {
            get {
                return ResourceManager.GetString("STA状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOD状态 的本地化字符串。
        /// </summary>
        internal static string TOD状态 {
            get {
                return ResourceManager.GetString("TOD状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VOBC车载主机状态 的本地化字符串。
        /// </summary>
        internal static string VOBC车载主机状态 {
            get {
                return ResourceManager.GetString("VOBC车载主机状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上站到下站偏移量 的本地化字符串。
        /// </summary>
        internal static string 上站到下站偏移量 {
            get {
                return ResourceManager.GetString("上站到下站偏移量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一目标 的本地化字符串。
        /// </summary>
        internal static string 下一目标 {
            get {
                return ResourceManager.GetString("下一目标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一站 的本地化字符串。
        /// </summary>
        internal static string 下一站 {
            get {
                return ResourceManager.GetString("下一站", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信号制动状态 的本地化字符串。
        /// </summary>
        internal static string 信号制动状态 {
            get {
                return ResourceManager.GetString("信号制动状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信标状态 的本地化字符串。
        /// </summary>
        internal static string 信标状态 {
            get {
                return ResourceManager.GetString("信标状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停站时间 的本地化字符串。
        /// </summary>
        internal static string 停站时间 {
            get {
                return ResourceManager.GetString("停站时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停车状态 的本地化字符串。
        /// </summary>
        internal static string 停车状态 {
            get {
                return ResourceManager.GetString("停车状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出入库预告 的本地化字符串。
        /// </summary>
        internal static string 出入库预告 {
            get {
                return ResourceManager.GetString("出入库预告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切除牵引速度 的本地化字符串。
        /// </summary>
        internal static string 切除牵引速度 {
            get {
                return ResourceManager.GetString("切除牵引速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车下一区段所在区域 的本地化字符串。
        /// </summary>
        internal static string 列车下一区段所在区域 {
            get {
                return ResourceManager.GetString("列车下一区段所在区域", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车前一区段所在区域 的本地化字符串。
        /// </summary>
        internal static string 列车前一区段所在区域 {
            get {
                return ResourceManager.GetString("列车前一区段所在区域", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车号 的本地化字符串。
        /// </summary>
        internal static string 列车号 {
            get {
                return ResourceManager.GetString("列车号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车回段停车后提示信息 的本地化字符串。
        /// </summary>
        internal static string 列车回段停车后提示信息 {
            get {
                return ResourceManager.GetString("列车回段停车后提示信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车当前所在区域 的本地化字符串。
        /// </summary>
        internal static string 列车当前所在区域 {
            get {
                return ResourceManager.GetString("列车当前所在区域", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车报警速度 的本地化字符串。
        /// </summary>
        internal static string 列车报警速度 {
            get {
                return ResourceManager.GetString("列车报警速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车推荐速度 的本地化字符串。
        /// </summary>
        internal static string 列车推荐速度 {
            get {
                return ResourceManager.GetString("列车推荐速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车早晚点 的本地化字符串。
        /// </summary>
        internal static string 列车早晚点 {
            get {
                return ResourceManager.GetString("列车早晚点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车目标速度 的本地化字符串。
        /// </summary>
        internal static string 列车目标速度 {
            get {
                return ResourceManager.GetString("列车目标速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车紧急速度 的本地化字符串。
        /// </summary>
        internal static string 列车紧急速度 {
            get {
                return ResourceManager.GetString("列车紧急速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车运行速度 的本地化字符串。
        /// </summary>
        internal static string 列车运行速度 {
            get {
                return ResourceManager.GetString("列车运行速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车长度 的本地化字符串。
        /// </summary>
        internal static string 列车长度 {
            get {
                return ResourceManager.GetString("列车长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车限制速度 的本地化字符串。
        /// </summary>
        internal static string 列车限制速度 {
            get {
                return ResourceManager.GetString("列车限制速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到下一站时间 的本地化字符串。
        /// </summary>
        internal static string 到下一站时间 {
            get {
                return ResourceManager.GetString("到下一站时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到达时间 的本地化字符串。
        /// </summary>
        internal static string 到达时间 {
            get {
                return ResourceManager.GetString("到达时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前方信号机状态 的本地化字符串。
        /// </summary>
        internal static string 前方信号机状态 {
            get {
                return ResourceManager.GetString("前方信号机状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前方信号机距离 的本地化字符串。
        /// </summary>
        internal static string 前方信号机距离 {
            get {
                return ResourceManager.GetString("前方信号机距离", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前车距离 的本地化字符串。
        /// </summary>
        internal static string 前车距离 {
            get {
                return ResourceManager.GetString("前车距离", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单程号 的本地化字符串。
        /// </summary>
        internal static string 单程号 {
            get {
                return ResourceManager.GetString("单程号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发车时间 的本地化字符串。
        /// </summary>
        internal static string 发车时间 {
            get {
                return ResourceManager.GetString("发车时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发车状态 的本地化字符串。
        /// </summary>
        internal static string 发车状态 {
            get {
                return ResourceManager.GetString("发车状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右侧车门状态 的本地化字符串。
        /// </summary>
        internal static string 右侧车门状态 {
            get {
                return ResourceManager.GetString("右侧车门状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右车门允许 的本地化字符串。
        /// </summary>
        internal static string 右车门允许 {
            get {
                return ResourceManager.GetString("右车门允许", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 司机号 的本地化字符串。
        /// </summary>
        internal static string 司机号 {
            get {
                return ResourceManager.GetString("司机号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 司机号字母 的本地化字符串。
        /// </summary>
        internal static string 司机号字母 {
            get {
                return ResourceManager.GetString("司机号字母", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后车距离 的本地化字符串。
        /// </summary>
        internal static string 后车距离 {
            get {
                return ResourceManager.GetString("后车距离", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左侧车门状态 的本地化字符串。
        /// </summary>
        internal static string 左侧车门状态 {
            get {
                return ResourceManager.GetString("左侧车门状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左车门允许 的本地化字符串。
        /// </summary>
        internal static string 左车门允许 {
            get {
                return ResourceManager.GetString("左车门允许", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前站 的本地化字符串。
        /// </summary>
        internal static string 当前站 {
            get {
                return ResourceManager.GetString("当前站", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折返信息 的本地化字符串。
        /// </summary>
        internal static string 折返信息 {
            get {
                return ResourceManager.GetString("折返信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控车类型 的本地化字符串。
        /// </summary>
        internal static string 控车类型 {
            get {
                return ResourceManager.GetString("控车类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无线连接状态 的本地化字符串。
        /// </summary>
        internal static string 无线连接状态 {
            get {
                return ResourceManager.GetString("无线连接状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示的日期 的本地化字符串。
        /// </summary>
        internal static string 显示的日期 {
            get {
                return ResourceManager.GetString("显示的日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示的时间 的本地化字符串。
        /// </summary>
        internal static string 显示的时间 {
            get {
                return ResourceManager.GetString("显示的时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务号 的本地化字符串。
        /// </summary>
        internal static string 服务号 {
            get {
                return ResourceManager.GetString("服务号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机车信号码 的本地化字符串。
        /// </summary>
        internal static string 机车信号码 {
            get {
                return ResourceManager.GetString("机车信号码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标距离 的本地化字符串。
        /// </summary>
        internal static string 目标距离 {
            get {
                return ResourceManager.GetString("目标距离", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的地号 的本地化字符串。
        /// </summary>
        internal static string 目的地号 {
            get {
                return ResourceManager.GetString("目的地号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的地号字母 的本地化字符串。
        /// </summary>
        internal static string 目的地号字母 {
            get {
                return ResourceManager.GetString("目的地号字母", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动授权 的本地化字符串。
        /// </summary>
        internal static string 移动授权 {
            get {
                return ResourceManager.GetString("移动授权", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空转指示 的本地化字符串。
        /// </summary>
        internal static string 空转指示 {
            get {
                return ResourceManager.GetString("空转指示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统状态 的本地化字符串。
        /// </summary>
        internal static string 系统状态 {
            get {
                return ResourceManager.GetString("系统状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线路号 的本地化字符串。
        /// </summary>
        internal static string 线路号 {
            get {
                return ResourceManager.GetString("线路号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终点站 的本地化字符串。
        /// </summary>
        internal static string 终点站 {
            get {
                return ResourceManager.GetString("终点站", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编组 的本地化字符串。
        /// </summary>
        internal static string 编组 {
            get {
                return ResourceManager.GetString("编组", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距前车运行时分 的本地化字符串。
        /// </summary>
        internal static string 距前车运行时分 {
            get {
                return ResourceManager.GetString("距前车运行时分", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距后车运行时分 的本地化字符串。
        /// </summary>
        internal static string 距后车运行时分 {
            get {
                return ResourceManager.GetString("距后车运行时分", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径号 的本地化字符串。
        /// </summary>
        internal static string 路径号 {
            get {
                return ResourceManager.GetString("路径号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车尾OBCU 的本地化字符串。
        /// </summary>
        internal static string 车尾OBCU {
            get {
                return ResourceManager.GetString("车尾OBCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车次号 的本地化字符串。
        /// </summary>
        internal static string 车次号 {
            get {
                return ResourceManager.GetString("车次号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车次号字母 的本地化字符串。
        /// </summary>
        internal static string 车次号字母 {
            get {
                return ResourceManager.GetString("车次号字母", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车站控车状态 的本地化字符串。
        /// </summary>
        internal static string 车站控车状态 {
            get {
                return ResourceManager.GetString("车站控车状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车载定位状态 的本地化字符串。
        /// </summary>
        internal static string 车载定位状态 {
            get {
                return ResourceManager.GetString("车载定位状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车载系统与调度中心通信状态 的本地化字符串。
        /// </summary>
        internal static string 车载系统与调度中心通信状态 {
            get {
                return ResourceManager.GetString("车载系统与调度中心通信状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车载运行模式 的本地化字符串。
        /// </summary>
        internal static string 车载运行模式 {
            get {
                return ResourceManager.GetString("车载运行模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆实时运行工况 的本地化字符串。
        /// </summary>
        internal static string 车辆实时运行工况 {
            get {
                return ResourceManager.GetString("车辆实时运行工况", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车首OBCU 的本地化字符串。
        /// </summary>
        internal static string 车首OBCU {
            get {
                return ResourceManager.GetString("车首OBCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行方向 的本地化字符串。
        /// </summary>
        internal static string 运行方向 {
            get {
                return ResourceManager.GetString("运行方向", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进出折返预告 的本地化字符串。
        /// </summary>
        internal static string 进出折返预告 {
            get {
                return ResourceManager.GetString("进出折返预告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进路预选区终点距离 的本地化字符串。
        /// </summary>
        internal static string 进路预选区终点距离 {
            get {
                return ResourceManager.GetString("进路预选区终点距离", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度指示 的本地化字符串。
        /// </summary>
        internal static string 速度指示 {
            get {
                return ResourceManager.GetString("速度指示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 障碍物左右偏移1 的本地化字符串。
        /// </summary>
        internal static string 障碍物左右偏移1 {
            get {
                return ResourceManager.GetString("障碍物左右偏移1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 障碍物左右偏移2 的本地化字符串。
        /// </summary>
        internal static string 障碍物左右偏移2 {
            get {
                return ResourceManager.GetString("障碍物左右偏移2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 障碍物左右偏移3 的本地化字符串。
        /// </summary>
        internal static string 障碍物左右偏移3 {
            get {
                return ResourceManager.GetString("障碍物左右偏移3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 障碍物距离1 的本地化字符串。
        /// </summary>
        internal static string 障碍物距离1 {
            get {
                return ResourceManager.GetString("障碍物距离1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 障碍物距离2 的本地化字符串。
        /// </summary>
        internal static string 障碍物距离2 {
            get {
                return ResourceManager.GetString("障碍物距离2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 障碍物距离3 的本地化字符串。
        /// </summary>
        internal static string 障碍物距离3 {
            get {
                return ResourceManager.GetString("障碍物距离3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷达状态 的本地化字符串。
        /// </summary>
        internal static string 雷达状态 {
            get {
                return ResourceManager.GetString("雷达状态", resourceCulture);
            }
        }
    }
}
