//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urban.QingDao3Line.MMI.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MMIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MMIResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Urban.QingDao3Line.MMI.Resource.MMIResource", typeof(MMIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Acceleration has been activated 的本地化字符串。
        /// </summary>
        public static string AccelerationHasActivation {
            get {
                return ResourceManager.GetString("AccelerationHasActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string CommonUserNo {
            get {
                return ResourceManager.GetString("CommonUserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string CommonUserYes {
            get {
                return ResourceManager.GetString("CommonUserYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Communication bus fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceCommunicationbusfault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceCommunicationbusfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DCU5 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDCU5 {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDCU5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diadnose memory fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDiadnosememoryfault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDiadnosememoryfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door close switch fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDoorcloseswitchfault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDoorcloseswitchfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door driving motor fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDoordrivingmotorfault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDoordrivingmotorfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door locked device fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDoorlockeddevicefault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDoorlockeddevicefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door lock switch fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDoorlockswitchfault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDoorlockswitchfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door not unlocked within 3 sec 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDoornotunlockedwithin3sec {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDoornotunlockedwithin3sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door position not permited 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDoorpositionnotpermited {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDoorpositionnotpermited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door position sensor fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDoorpositionsensorfault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDoorpositionsensorfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door safet loop fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDoorsafetloopfault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDoorsafetloopfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door safety relay fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceDoorsafetyrelayfault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceDoorsafetyrelayfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gateway 1 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceGateway1 {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceGateway1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gateway 2 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceGateway2 {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceGateway2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M2 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceM2 {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium OK A 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceMediumOKA {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceMediumOKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium OK B 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceMediumOKB {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceMediumOKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obstacle detected during closing 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceObstacledetectedduringclosing {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceObstacledetectedduringclosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obstacle detected during openging 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceObstacledetectedduringopenging {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceObstacledetectedduringopenging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 0 fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceOutput0fault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceOutput0fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 1 fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceOutput1fault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceOutput1fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 2 fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceOutput2fault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceOutput2fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 3 fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceOutput3fault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceOutput3fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 4 fault 的本地化字符串。
        /// </summary>
        public static string DoorsMaintenanceResourceOutput4fault {
            get {
                return ResourceManager.GetString("DoorsMaintenanceResourceOutput4fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATO 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceATO {
            get {
                return ResourceManager.GetString("DrivingViewResourceATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At Least 2 Brakes Isolated \nPlease go back to The Depot 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceBCULosing {
            get {
                return ResourceManager.GetString("DrivingViewResourceBCULosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake Effort Achieved 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceBrakeEffortAchieved {
            get {
                return ResourceManager.GetString("DrivingViewResourceBrakeEffortAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake Effort Demand 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceBrakeEffortDemand {
            get {
                return ResourceManager.GetString("DrivingViewResourceBrakeEffortDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Break Off 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceBreaking {
            get {
                return ResourceManager.GetString("DrivingViewResourceBreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ByPass 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceByPass {
            get {
                return ResourceManager.GetString("DrivingViewResourceByPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy.MM.dd 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceDateFormat {
            get {
                return ResourceManager.GetString("DrivingViewResourceDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The equipment is not operational or disconnected.\n Do not take into account informations of this equipment.\n Switch to Backup mode 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceErrorInfo {
            get {
                return ResourceManager.GetString("DrivingViewResourceErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final Station: 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceFinalStation {
            get {
                return ResourceManager.GetString("DrivingViewResourceFinalStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IOS : 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceIOS {
            get {
                return ResourceManager.GetString("DrivingViewResourceIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 km/h 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourcekmPerh {
            get {
                return ResourceManager.GetString("DrivingViewResourcekmPerh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limitting Back 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceLimittingBack {
            get {
                return ResourceManager.GetString("DrivingViewResourceLimittingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limitting Forward 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceLimittingForward {
            get {
                return ResourceManager.GetString("DrivingViewResourceLimittingForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Of The Car 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceLoadOfTheCar {
            get {
                return ResourceManager.GetString("DrivingViewResourceLoadOfTheCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceManual {
            get {
                return ResourceManager.GetString("DrivingViewResourceManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPR1 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceMPR1 {
            get {
                return ResourceManager.GetString("DrivingViewResourceMPR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPR2 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceMPR2 {
            get {
                return ResourceManager.GetString("DrivingViewResourceMPR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Station: 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceNextStation {
            get {
                return ResourceManager.GetString("DrivingViewResourceNextStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please go back to The Depot 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourcePleaseBack {
            get {
                return ResourceManager.GetString("DrivingViewResourcePleaseBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RIOM KO 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceRIOM {
            get {
                return ResourceManager.GetString("DrivingViewResourceRIOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SB Pressure 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSBPressure {
            get {
                return ResourceManager.GetString("DrivingViewResourceSBPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKATP 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKATP {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKCDB 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKCDB {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKCDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKDMB 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKDMB {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKDMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKEBB 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKEBB {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKEBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKESS 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKESS {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKMPB 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKMPB {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKMPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKNRB 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKNRB {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKNRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKPRB 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKPRB {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKPRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKTDB 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKTDB {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKTDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKTIB 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKTIB {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKTIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKTPB 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKTPB {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKTPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKZVB 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceSKZVB {
            get {
                return ResourceManager.GetString("DrivingViewResourceSKZVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HH:mm:ss 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceTimeFormat {
            get {
                return ResourceManager.GetString("DrivingViewResourceTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traction/Brake Effort 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceTractionBrakeEffort {
            get {
                return ResourceManager.GetString("DrivingViewResourceTractionBrakeEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traction Effort Achieved 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceTractionEffortAchieved {
            get {
                return ResourceManager.GetString("DrivingViewResourceTractionEffortAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traction Effort Demand 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceTractionEffortDemand {
            get {
                return ResourceManager.GetString("DrivingViewResourceTractionEffortDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wash Train 的本地化字符串。
        /// </summary>
        public static string DrivingViewResourceWashing {
            get {
                return ResourceManager.GetString("DrivingViewResourceWashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        public static string MaintenanceAirCopressorcsResourceCommand {
            get {
                return ResourceManager.GetString("MaintenanceAirCopressorcsResourceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor control Tc1 的本地化字符串。
        /// </summary>
        public static string MaintenanceAirCopressorcsResourceCompressorcontrolTc1 {
            get {
                return ResourceManager.GetString("MaintenanceAirCopressorcsResourceCompressorcontrolTc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor control Tc2 的本地化字符串。
        /// </summary>
        public static string MaintenanceAirCopressorcsResourceCompressorcontrolTc2 {
            get {
                return ResourceManager.GetString("MaintenanceAirCopressorcsResourceCompressorcontrolTc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceAirCopressorcsResourceInfault {
            get {
                return ResourceManager.GetString("MaintenanceAirCopressorcsResourceInfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runing 的本地化字符串。
        /// </summary>
        public static string MaintenanceAirCopressorcsResourceRuning {
            get {
                return ResourceManager.GetString("MaintenanceAirCopressorcsResourceRuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACE1 ACE2 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceACE1ACE2 {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceACE1ACE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anflow low level detection 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceAnflowlowleveldetection {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceAnflowlowleveldetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coupling Contactor 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceCouplingContactor {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceCouplingContactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical Fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceCriticalFault {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceCriticalFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CVS1 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceCVS1A501 {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceCVS1A501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CVS2 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceCVS2A501 {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceCVS2A501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CVS is correstly running 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceCVSiscorrestlyrunning {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceCVSiscorrestlyrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CVS Scheme 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceCVSScheme {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceCVSScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fault Event 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceFaultEvent {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceFaultEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input block pemanent fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceInputblockpemanentfault {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceInputblockpemanentfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inverter out of service 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceInverteroutofservice {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceInverteroutofservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of faults 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceListoffaults {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceListoffaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance:Air Compressor 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceMaintenanceAirCompressor {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceMaintenanceAirCompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaintenanceAuxiliary 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceMaintenanceAuxiliary {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceMaintenanceAuxiliary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintence: SoftWare Version 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceMaintenanceSoftWareVersion {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceMaintenanceSoftWareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major Fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceMajorFault {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceMajorFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minor Fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceMinorFault {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceMinorFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVB communication 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceMVBcommunication {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceMVBcommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFF 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceOFF {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ON 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceON {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset CVS1 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceResetCVS1 {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceResetCVS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset CVS2 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceResetCVS2 {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceResetCVS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse CVS Switch 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceReverseCVSSwitch {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceReverseCVSSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 States 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceStates {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop CVS Switch 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceStopCVSSwitch {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceStopCVSSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trasfimer themal image fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceAuxiliaryResourceTrasfimerthemalimagefault {
            get {
                return ResourceManager.GetString("MaintenanceAuxiliaryResourceTrasfimerthemalimagefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effort Achieved 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceEffortAchieved {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceEffortAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effort Demand 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceEffortDemand {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceEffortDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effort Possible 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceEffortPossible {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceEffortPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Energy Consumed 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceEnergyConsumed {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceEnergyConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnergyRegenerated 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceEnergyRegenerated {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceEnergyRegenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GTW1 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceGTW1 {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceGTW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GTW2 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceGTW2 {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceGTW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GTW3 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceGTW3 {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceGTW3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GTW4 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceGTW4 {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceGTW4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ----kN 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourcekN {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourcekN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ---- kWh 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourcekWh {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourcekWh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPU 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceMPU {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceMPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVB communication 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceMVBcommunication {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceMVBcommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operational 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceOperational {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceOperational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCE1 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourcePCE1 {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourcePCE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCE2 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourcePCE2 {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourcePCE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCE3 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourcePCE3 {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourcePCE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCE4 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourcePCE4 {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourcePCE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOTAL 的本地化字符串。
        /// </summary>
        public static string MaintenanceBasicResourceTOTAL {
            get {
                return ResourceManager.GetString("MaintenanceBasicResourceTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery 1 capacity 的本地化字符串。
        /// </summary>
        public static string MaintenanceBaterryResourceBattery1capacity {
            get {
                return ResourceManager.GetString("MaintenanceBaterryResourceBattery1capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery 2 capacity 的本地化字符串。
        /// </summary>
        public static string MaintenanceBaterryResourceBattery2capacity {
            get {
                return ResourceManager.GetString("MaintenanceBaterryResourceBattery2capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NOK 的本地化字符串。
        /// </summary>
        public static string MaintenanceBaterryResourceNOK {
            get {
                return ResourceManager.GetString("MaintenanceBaterryResourceNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string MaintenanceBaterryResourceOK {
            get {
                return ResourceManager.GetString("MaintenanceBaterryResourceOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance: Battery 的本地化字符串。
        /// </summary>
        public static string MaintenanceBattery {
            get {
                return ResourceManager.GetString("MaintenanceBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        public static string MaintenanceBlackBoxResourceData {
            get {
                return ResourceManager.GetString("MaintenanceBlackBoxResourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance Allowed Between Trains 的本地化字符串。
        /// </summary>
        public static string MaintenanceBlackBoxResourceTrainDistance {
            get {
                return ResourceManager.GetString("MaintenanceBlackBoxResourceTrainDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Train Speed 的本地化字符串。
        /// </summary>
        public static string MaintenanceBlackBoxResourceTrainSpeed {
            get {
                return ResourceManager.GetString("MaintenanceBlackBoxResourceTrainSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wheel Diameter 的本地化字符串。
        /// </summary>
        public static string MaintenanceBlackBoxResourceWheelDiameter {
            get {
                return ResourceManager.GetString("MaintenanceBlackBoxResourceWheelDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breaking Command TrainLines 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceBreakingCommandTrainLines {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceBreakingCommandTrainLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIA_BOARD_CB09A_1 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceDIA_BOARD_CB09A_1 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceDIA_BOARD_CB09A_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIA_DV_AXLE_1_HOLD 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceDIA_DV_AXLE_1_HOLD {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceDIA_DV_AXLE_1_HOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIA_PRESSURE-UP-3 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceDIA_PRESSURE_UP_3 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceDIA_PRESSURE_UP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIA_RELAY_MAJOR_EVENT 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceDIA_RELAY_MAJOR_EVENT {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceDIA_RELAY_MAJOR_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIA-RELAY-ZERO-SPEED 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceDIA_RELAY_ZERO_SPEED {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceDIA_RELAY_ZERO_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dragging Accredit TraiLines 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceDraggingAccreditTrainLines {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceDraggingAccreditTrainLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dragging TrainLines 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceDraggingTrainLines {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceDraggingTrainLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FalutEvent 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceFalutEvent {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceFalutEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FaultEvent 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceFaultEvent {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceFaultEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GTW1 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceGTW1 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceGTW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GTW2 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceGTW2 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceGTW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GTW3 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceGTW3 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceGTW3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GTW4 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceGTW4 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceGTW4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of faults 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceListoffaults {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceListoffaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M1 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceM1 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M2 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceM2 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M3 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceM3 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M4 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceM4 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major Fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceMajorFault {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceMajorFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minor Fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceMinorFault {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceMinorFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVB Communication 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceMVBCommunication {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceMVBCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserve Mode TrainLines 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceReserveTrainLines {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceReserveTrainLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self  Test 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceSelfTest {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceSelfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self Test Condition:  的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceSelfTestCondition {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceSelfTestCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 START 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceSTART {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting condition 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceStartingcondition {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceStartingcondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 States 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceStates {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tc1 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceTc1 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceTc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tc2 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceTc2 {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceTc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test in progress 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceTestinprogress {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceTestinprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test result 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceTestresult {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceTestresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To be define 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceTobedefine {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceTobedefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrainLines 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceTrainLines {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceTrainLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Urgent Breaking TrainLines 的本地化字符串。
        /// </summary>
        public static string MaintenanceBrakeResourceUrgentBreakingTrainLines {
            get {
                return ResourceManager.GetString("MaintenanceBrakeResourceUrgentBreakingTrainLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceAutomatic {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor 1 high pressure 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCompressor1highpressure {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCompressor1highpressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor 1 low pressure 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCompressor1lowpressure {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCompressor1lowpressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor 1 overcurrent 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCompressor1overcurrent {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCompressor1overcurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor 1 temp fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCompressor1tempfault {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCompressor1tempfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor 2 high pressure 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCompressor2highpressure {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCompressor2highpressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor 2 low  pressure 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCompressor2lowpressure {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCompressor2lowpressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor 2 overcurrent 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCompressor2overcurrent {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCompressor2overcurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor 2 temp fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCompressor2tempfault {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCompressor2tempfault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condsender 1 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCondsender1 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCondsender1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condsender 2 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCondsender2 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCondsender2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cooling 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceCooling {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency ventilation 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceEmergencyVentilation {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceEmergencyVentilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment mode 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceEquipmentmode {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceEquipmentmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaporator 1 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceEvaporator1 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceEvaporator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaporator 2 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceEvaporator2 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceEvaporator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fresh air temperature 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceFreshairtemperature {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceFreshairtemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceMaintenance {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceOff {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reduce 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceReduce {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return air temperature 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceReturnairtemperature {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceReturnairtemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit1 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceUnit1 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceUnit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit2 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceUnit2 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceUnit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAC1 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVAC1 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVAC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAC2 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVAC2 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVAC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAC3 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVAC3 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVAC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAC4 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVAC4 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVAC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAC5 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVAC5 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVAC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAC6 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVAC6 {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVAC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Central Control 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVACCentralControl {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVACCentralControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Cooling 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVACFullCooling {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVACFullCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Half Cooling 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVACHalfCooling {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVACHalfCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance Status 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVACMaintenance {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVACMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off Status 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVACOff {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVACOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAC switch sattus 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVACswitchsattus {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVACswitchsattus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ventilation Status 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVACVentilation {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVACVentilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ventilation 的本地化字符串。
        /// </summary>
        public static string MaintenanceHVACResourceVentilation {
            get {
                return ResourceManager.GetString("MaintenanceHVACResourceVentilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIS1 的本地化字符串。
        /// </summary>
        public static string MaintenancePassengerInformationPIS1 {
            get {
                return ResourceManager.GetString("MaintenancePassengerInformationPIS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIS2 的本地化字符串。
        /// </summary>
        public static string MaintenancePassengerInformationPIS2 {
            get {
                return ResourceManager.GetString("MaintenancePassengerInformationPIS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIS State 的本地化字符串。
        /// </summary>
        public static string MaintenancePassengerInformationPISState {
            get {
                return ResourceManager.GetString("MaintenancePassengerInformationPISState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access to software configuration information 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceAccessToSoftwareConfigurationInformation {
            get {
                return ResourceManager.GetString("MaintenanceResourceAccessToSoftwareConfigurationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller Unit Fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceControllerFault {
            get {
                return ResourceManager.GetString("MaintenanceResourceControllerFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host/Guest 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceHostAndGuest {
            get {
                return ResourceManager.GetString("MaintenanceResourceHostAndGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance:Basic Information 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceMaintenanceBaseInformation {
            get {
                return ResourceManager.GetString("MaintenanceResourceMaintenanceBaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BBO1 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceMaintenanceBBO1 {
            get {
                return ResourceManager.GetString("MaintenanceResourceMaintenanceBBO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BBO2 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceMaintenanceBBO2 {
            get {
                return ResourceManager.GetString("MaintenanceResourceMaintenanceBBO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance:Black Box 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceMaintenanceBlackBox {
            get {
                return ResourceManager.GetString("MaintenanceResourceMaintenanceBlackBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance: Brake 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceMaintenanceBrake {
            get {
                return ResourceManager.GetString("MaintenanceResourceMaintenanceBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenace: Doors 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceMaintenanceDoors {
            get {
                return ResourceManager.GetString("MaintenanceResourceMaintenanceDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance:function selector 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceMaintenancefunctionselector {
            get {
                return ResourceManager.GetString("MaintenanceResourceMaintenancefunctionselector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance:HVAC 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceMaintenanceHVAC {
            get {
                return ResourceManager.GetString("MaintenanceResourceMaintenanceHVAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVB Net 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceMaintenanceMVBNet {
            get {
                return ResourceManager.GetString("MaintenanceResourceMaintenanceMVBNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance:Traction 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourceMaintenanceTraction {
            get {
                return ResourceManager.GetString("MaintenanceResourceMaintenanceTraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance:Passenger Information System 的本地化字符串。
        /// </summary>
        public static string MaintenanceResourcePassengerInformation {
            get {
                return ResourceManager.GetString("MaintenanceResourcePassengerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RIOM Select 的本地化字符串。
        /// </summary>
        public static string MaintenanceResoursRIOMSelect {
            get {
                return ResourceManager.GetString("MaintenanceResoursRIOMSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A B A B A B A B 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourceABABABAB {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourceABABABAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access to authonised maintenance mode conditions:fast 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourceAccesstoauthonisedmaintenancemodeconditionsfast {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourceAccesstoauthonisedmaintenancemodeconditionsfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 brake applied and vellocity null 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourcebrakeappliedandvellocitynull {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourcebrakeappliedandvellocitynull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical Fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourceCriticalFault {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourceCriticalFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of faults 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourceListoffaults {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourceListoffaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaintenanceTractionResource 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourceMaintenanceTraction {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourceMaintenanceTraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major Fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourceMajorFault {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourceMajorFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minor Fault 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourceMinorFault {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourceMinorFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVB channel A and channel B status 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourceMVBchannelAandchannelBstatus {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourceMVBchannelAandchannelBstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVB Communication 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourceMVBCorrespond {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourceMVBCorrespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCE1 PCE2 PCE3 PCE4 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourcePCE1PCE2PCE3PCE4 {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourcePCE1PCE2PCE3PCE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCE States 的本地化字符串。
        /// </summary>
        public static string MaintenanceTractionResourcePCEStates {
            get {
                return ResourceManager.GetString("MaintenanceTractionResourcePCEStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All doors closed and locked 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceAlldoorsclosedandlocked {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceAlldoorsclosedandlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority of driver to open doors 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceAuthorityofdrivertoopendoors {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceAuthorityofdrivertoopendoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization to open left doors 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceAuthorizationtoopenleftdoors {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceAuthorizationtoopenleftdoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization to open right doors 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceAuthorizationtoopenrightdoors {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceAuthorizationtoopenrightdoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door close status side A 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceDoorclosestatussideA {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceDoorclosestatussideA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door close status side B 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceDoorclosestatussideB {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceDoorclosestatussideB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M1 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceM1 {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M2 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceM2 {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M3 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceM3 {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M4 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceM4 {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request left door closed 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceRequestleftdoorclosed {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceRequestleftdoorclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request left door opened 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceRequestleftdooropened {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceRequestleftdooropened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request right door closed 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceRequestrightdoorclosed {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceRequestrightdoorclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request right door opened 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceRequestrightdooropened {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceRequestrightdooropened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tc1 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceTc1 {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceTc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tc2 的本地化字符串。
        /// </summary>
        public static string MaintenanceTrainLineResourceTc2 {
            get {
                return ResourceManager.GetString("MaintenanceTrainLineResourceTc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acceleration Test 的本地化字符串。
        /// </summary>
        public static string MaintenceAccelerateTest {
            get {
                return ResourceManager.GetString("MaintenceAccelerateTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average Acceleration 的本地化字符串。
        /// </summary>
        public static string MaintenceAverageAcceleration {
            get {
                return ResourceManager.GetString("MaintenceAverageAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average Reduce 的本地化字符串。
        /// </summary>
        public static string MaintenceAverageReduce {
            get {
                return ResourceManager.GetString("MaintenceAverageReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brake Distance 的本地化字符串。
        /// </summary>
        public static string MaintenceBrakeDistance {
            get {
                return ResourceManager.GetString("MaintenceBrakeDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag And Brake 的本地化字符串。
        /// </summary>
        public static string MaintenceDragAndBrake {
            get {
                return ResourceManager.GetString("MaintenceDragAndBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed Cut Test 的本地化字符串。
        /// </summary>
        public static string MaintenceReduceTest {
            get {
                return ResourceManager.GetString("MaintenceReduceTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Speed 的本地化字符串。
        /// </summary>
        public static string MaintenceTargetSpeed {
            get {
                return ResourceManager.GetString("MaintenceTargetSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date And Time 的本地化字符串。
        /// </summary>
        public static string MPUEventDateAndTime {
            get {
                return ResourceManager.GetString("MPUEventDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string MPUEventDescription {
            get {
                return ResourceManager.GetString("MPUEventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPU Events List 的本地化字符串。
        /// </summary>
        public static string MPUEventList {
            get {
                return ResourceManager.GetString("MPUEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        public static string MPUEventLocation {
            get {
                return ResourceManager.GetString("MPUEventLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        public static string MPUEventResourceEvents {
            get {
                return ResourceManager.GetString("MPUEventResourceEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page 的本地化字符串。
        /// </summary>
        public static string MPUEventResourcePage {
            get {
                return ResourceManager.GetString("MPUEventResourcePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReLoad 的本地化字符串。
        /// </summary>
        public static string MPUEventResourceReLoad {
            get {
                return ResourceManager.GetString("MPUEventResourceReLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stack Name 的本地化字符串。
        /// </summary>
        public static string MPUEventStackName {
            get {
                return ResourceManager.GetString("MPUEventStackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string PISResourceMessage {
            get {
                return ResourceManager.GetString("PISResourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEND 的本地化字符串。
        /// </summary>
        public static string PISResourceSEND {
            get {
                return ResourceManager.GetString("PISResourceSEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alarm detection 的本地化字符串。
        /// </summary>
        public static string SDIResourceAlarmdetection {
            get {
                return ResourceManager.GetString("SDIResourceAlarmdetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure state 的本地化字符串。
        /// </summary>
        public static string SDIResourceFailurestate {
            get {
                return ResourceManager.GetString("SDIResourceFailurestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M1 的本地化字符串。
        /// </summary>
        public static string SDIResourceM1 {
            get {
                return ResourceManager.GetString("SDIResourceM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M2 的本地化字符串。
        /// </summary>
        public static string SDIResourceM2 {
            get {
                return ResourceManager.GetString("SDIResourceM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M3 的本地化字符串。
        /// </summary>
        public static string SDIResourceM3 {
            get {
                return ResourceManager.GetString("SDIResourceM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M4 的本地化字符串。
        /// </summary>
        public static string SDIResourceM4 {
            get {
                return ResourceManager.GetString("SDIResourceM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-Alarm detection 的本地化字符串。
        /// </summary>
        public static string SDIResourcePre_Alarmdetection {
            get {
                return ResourceManager.GetString("SDIResourcePre_Alarmdetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDI 的本地化字符串。
        /// </summary>
        public static string SDIResourceSDI {
            get {
                return ResourceManager.GetString("SDIResourceSDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tc1 的本地化字符串。
        /// </summary>
        public static string SDIResourceTc1 {
            get {
                return ResourceManager.GetString("SDIResourceTc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tc2 的本地化字符串。
        /// </summary>
        public static string SDIResourceTc2 {
            get {
                return ResourceManager.GetString("SDIResourceTc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AIR\nPURIFICATION 的本地化字符串。
        /// </summary>
        public static string SettingResourceAIRPURIFICATION {
            get {
                return ResourceManager.GetString("SettingResourceAIRPURIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air temperature 的本地化字符串。
        /// </summary>
        public static string SettingResourceAirTemperature {
            get {
                return ResourceManager.GetString("SettingResourceAirTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Password : 的本地化字符串。
        /// </summary>
        public static string SettingResourceEnterPassword {
            get {
                return ResourceManager.GetString("SettingResourceEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HALF\nCOOLING 的本地化字符串。
        /// </summary>
        public static string SettingResourceHALFCOOLING {
            get {
                return ResourceManager.GetString("SettingResourceHALFCOOLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HVAC mode selection 的本地化字符串。
        /// </summary>
        public static string SettingResourceHVACModeSelection {
            get {
                return ResourceManager.GetString("SettingResourceHVACModeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OUTSIDE\nFIRE MODE 的本地化字符串。
        /// </summary>
        public static string SettingResourceOUTSIDFIREMODE {
            get {
                return ResourceManager.GetString("SettingResourceOUTSIDFIREMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protected\nMenu 的本地化字符串。
        /// </summary>
        public static string SettingResourceProtectedMenu {
            get {
                return ResourceManager.GetString("SettingResourceProtectedMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string TrainLineResourceConfirm {
            get {
                return ResourceManager.GetString("TrainLineResourceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Departure 的本地化字符串。
        /// </summary>
        public static string TrainLineResourceDeparture {
            get {
                return ResourceManager.GetString("TrainLineResourceDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destition 的本地化字符串。
        /// </summary>
        public static string TrainLineResourceDestition {
            get {
                return ResourceManager.GetString("TrainLineResourceDestition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skipped 的本地化字符串。
        /// </summary>
        public static string TrainLineResourceSkipped {
            get {
                return ResourceManager.GetString("TrainLineResourceSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Station 的本地化字符串。
        /// </summary>
        public static string TrainLineResourceStartStation {
            get {
                return ResourceManager.GetString("TrainLineResourceStartStation", resourceCulture);
            }
        }
    }
}
