//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motor.HMI.CRH380D.Resources.Keys {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InFolatKey {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InFolatKey() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motor.HMI.CRH380D.Resources.Keys.InFolatKey", typeof(InFolatKey).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 列车状态_制动力 的本地化字符串。
        /// </summary>
        internal static string 列车状态_制动力 {
            get {
                return ResourceManager.GetString("列车状态_制动力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车状态_牵引力 的本地化字符串。
        /// </summary>
        internal static string 列车状态_牵引力 {
            get {
                return ResourceManager.GetString("列车状态_牵引力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车状态_网侧电流 的本地化字符串。
        /// </summary>
        internal static string 列车状态_网侧电流 {
            get {
                return ResourceManager.GetString("列车状态_网侧电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列车状态_限速 的本地化字符串。
        /// </summary>
        internal static string 列车状态_限速 {
            get {
                return ResourceManager.GetString("列车状态_限速", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部温度 的本地化字符串。
        /// </summary>
        internal static string 外部温度 {
            get {
                return ResourceManager.GetString("外部温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 牵引变流器1力 的本地化字符串。
        /// </summary>
        internal static string 牵引变流器1力 {
            get {
                return ResourceManager.GetString("牵引变流器1力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 牵引变流器2力 的本地化字符串。
        /// </summary>
        internal static string 牵引变流器2力 {
            get {
                return ResourceManager.GetString("牵引变流器2力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电压 的本地化字符串。
        /// </summary>
        internal static string 电压 {
            get {
                return ResourceManager.GetString("电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流供电_4车位置1电压 的本地化字符串。
        /// </summary>
        internal static string 直流供电_4车位置1电压 {
            get {
                return ResourceManager.GetString("直流供电_4车位置1电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流供电_4车位置1电流 的本地化字符串。
        /// </summary>
        internal static string 直流供电_4车位置1电流 {
            get {
                return ResourceManager.GetString("直流供电_4车位置1电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流供电_4车位置2电压 的本地化字符串。
        /// </summary>
        internal static string 直流供电_4车位置2电压 {
            get {
                return ResourceManager.GetString("直流供电_4车位置2电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流供电_4车位置2电流 的本地化字符串。
        /// </summary>
        internal static string 直流供电_4车位置2电流 {
            get {
                return ResourceManager.GetString("直流供电_4车位置2电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流供电_5车位置1电压 的本地化字符串。
        /// </summary>
        internal static string 直流供电_5车位置1电压 {
            get {
                return ResourceManager.GetString("直流供电_5车位置1电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流供电_5车位置1电流 的本地化字符串。
        /// </summary>
        internal static string 直流供电_5车位置1电流 {
            get {
                return ResourceManager.GetString("直流供电_5车位置1电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流供电_5车位置2电压 的本地化字符串。
        /// </summary>
        internal static string 直流供电_5车位置2电压 {
            get {
                return ResourceManager.GetString("直流供电_5车位置2电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流供电_5车位置2电流 的本地化字符串。
        /// </summary>
        internal static string 直流供电_5车位置2电流 {
            get {
                return ResourceManager.GetString("直流供电_5车位置2电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流供电_平均电压 的本地化字符串。
        /// </summary>
        internal static string 直流供电_平均电压 {
            get {
                return ResourceManager.GetString("直流供电_平均电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网侧变流器电压 的本地化字符串。
        /// </summary>
        internal static string 网侧变流器电压 {
            get {
                return ResourceManager.GetString("网侧变流器电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0制动力 的本地化字符串。
        /// </summary>
        internal static string 车0制动力 {
            get {
                return ResourceManager.GetString("车0制动力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0制动力百分比 的本地化字符串。
        /// </summary>
        internal static string 车0制动力百分比 {
            get {
                return ResourceManager.GetString("车0制动力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0压力传感器压力值 的本地化字符串。
        /// </summary>
        internal static string 车0压力传感器压力值 {
            get {
                return ResourceManager.GetString("车0压力传感器压力值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0水箱水量 的本地化字符串。
        /// </summary>
        internal static string 车0水箱水量 {
            get {
                return ResourceManager.GetString("车0水箱水量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0温度 的本地化字符串。
        /// </summary>
        internal static string 车0温度 {
            get {
                return ResourceManager.GetString("车0温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0牵引力百分比 的本地化字符串。
        /// </summary>
        internal static string 车0牵引力百分比 {
            get {
                return ResourceManager.GetString("车0牵引力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0转向架温度 的本地化字符串。
        /// </summary>
        internal static string 车0转向架温度 {
            get {
                return ResourceManager.GetString("车0转向架温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0轴1温度 的本地化字符串。
        /// </summary>
        internal static string 车0轴1温度 {
            get {
                return ResourceManager.GetString("车0轴1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0轴2温度 的本地化字符串。
        /// </summary>
        internal static string 车0轴2温度 {
            get {
                return ResourceManager.GetString("车0轴2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0齿轮箱1温度 的本地化字符串。
        /// </summary>
        internal static string 车0齿轮箱1温度 {
            get {
                return ResourceManager.GetString("车0齿轮箱1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0齿轮箱2温度 的本地化字符串。
        /// </summary>
        internal static string 车0齿轮箱2温度 {
            get {
                return ResourceManager.GetString("车0齿轮箱2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0齿轮箱3温度 的本地化字符串。
        /// </summary>
        internal static string 车0齿轮箱3温度 {
            get {
                return ResourceManager.GetString("车0齿轮箱3温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0齿轮箱4温度 的本地化字符串。
        /// </summary>
        internal static string 车0齿轮箱4温度 {
            get {
                return ResourceManager.GetString("车0齿轮箱4温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0齿轮箱5温度 的本地化字符串。
        /// </summary>
        internal static string 车0齿轮箱5温度 {
            get {
                return ResourceManager.GetString("车0齿轮箱5温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0齿轮箱6温度 的本地化字符串。
        /// </summary>
        internal static string 车0齿轮箱6温度 {
            get {
                return ResourceManager.GetString("车0齿轮箱6温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0齿轮箱7温度 的本地化字符串。
        /// </summary>
        internal static string 车0齿轮箱7温度 {
            get {
                return ResourceManager.GetString("车0齿轮箱7温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车0齿轮箱8温度 的本地化字符串。
        /// </summary>
        internal static string 车0齿轮箱8温度 {
            get {
                return ResourceManager.GetString("车0齿轮箱8温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1制动力 的本地化字符串。
        /// </summary>
        internal static string 车1制动力 {
            get {
                return ResourceManager.GetString("车1制动力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1制动力百分比 的本地化字符串。
        /// </summary>
        internal static string 车1制动力百分比 {
            get {
                return ResourceManager.GetString("车1制动力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1压力传感器压力值 的本地化字符串。
        /// </summary>
        internal static string 车1压力传感器压力值 {
            get {
                return ResourceManager.GetString("车1压力传感器压力值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1水箱水量 的本地化字符串。
        /// </summary>
        internal static string 车1水箱水量 {
            get {
                return ResourceManager.GetString("车1水箱水量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1温度 的本地化字符串。
        /// </summary>
        internal static string 车1温度 {
            get {
                return ResourceManager.GetString("车1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1牵引力百分比 的本地化字符串。
        /// </summary>
        internal static string 车1牵引力百分比 {
            get {
                return ResourceManager.GetString("车1牵引力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1转向架温度 的本地化字符串。
        /// </summary>
        internal static string 车1转向架温度 {
            get {
                return ResourceManager.GetString("车1转向架温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1轴1温度 的本地化字符串。
        /// </summary>
        internal static string 车1轴1温度 {
            get {
                return ResourceManager.GetString("车1轴1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1轴2温度 的本地化字符串。
        /// </summary>
        internal static string 车1轴2温度 {
            get {
                return ResourceManager.GetString("车1轴2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1齿轮箱1温度 的本地化字符串。
        /// </summary>
        internal static string 车1齿轮箱1温度 {
            get {
                return ResourceManager.GetString("车1齿轮箱1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1齿轮箱2温度 的本地化字符串。
        /// </summary>
        internal static string 车1齿轮箱2温度 {
            get {
                return ResourceManager.GetString("车1齿轮箱2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1齿轮箱3温度 的本地化字符串。
        /// </summary>
        internal static string 车1齿轮箱3温度 {
            get {
                return ResourceManager.GetString("车1齿轮箱3温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1齿轮箱4温度 的本地化字符串。
        /// </summary>
        internal static string 车1齿轮箱4温度 {
            get {
                return ResourceManager.GetString("车1齿轮箱4温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1齿轮箱5温度 的本地化字符串。
        /// </summary>
        internal static string 车1齿轮箱5温度 {
            get {
                return ResourceManager.GetString("车1齿轮箱5温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1齿轮箱6温度 的本地化字符串。
        /// </summary>
        internal static string 车1齿轮箱6温度 {
            get {
                return ResourceManager.GetString("车1齿轮箱6温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1齿轮箱7温度 的本地化字符串。
        /// </summary>
        internal static string 车1齿轮箱7温度 {
            get {
                return ResourceManager.GetString("车1齿轮箱7温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车1齿轮箱8温度 的本地化字符串。
        /// </summary>
        internal static string 车1齿轮箱8温度 {
            get {
                return ResourceManager.GetString("车1齿轮箱8温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2制动力 的本地化字符串。
        /// </summary>
        internal static string 车2制动力 {
            get {
                return ResourceManager.GetString("车2制动力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2制动力百分比 的本地化字符串。
        /// </summary>
        internal static string 车2制动力百分比 {
            get {
                return ResourceManager.GetString("车2制动力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2水箱水量 的本地化字符串。
        /// </summary>
        internal static string 车2水箱水量 {
            get {
                return ResourceManager.GetString("车2水箱水量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2污物箱量 的本地化字符串。
        /// </summary>
        internal static string 车2污物箱量 {
            get {
                return ResourceManager.GetString("车2污物箱量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2温度 的本地化字符串。
        /// </summary>
        internal static string 车2温度 {
            get {
                return ResourceManager.GetString("车2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2牵引力百分比 的本地化字符串。
        /// </summary>
        internal static string 车2牵引力百分比 {
            get {
                return ResourceManager.GetString("车2牵引力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2电压 的本地化字符串。
        /// </summary>
        internal static string 车2电压 {
            get {
                return ResourceManager.GetString("车2电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2电流 的本地化字符串。
        /// </summary>
        internal static string 车2电流 {
            get {
                return ResourceManager.GetString("车2电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2转向架温度 的本地化字符串。
        /// </summary>
        internal static string 车2转向架温度 {
            get {
                return ResourceManager.GetString("车2转向架温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2轴1温度 的本地化字符串。
        /// </summary>
        internal static string 车2轴1温度 {
            get {
                return ResourceManager.GetString("车2轴1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2轴2温度 的本地化字符串。
        /// </summary>
        internal static string 车2轴2温度 {
            get {
                return ResourceManager.GetString("车2轴2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2齿轮箱1温度 的本地化字符串。
        /// </summary>
        internal static string 车2齿轮箱1温度 {
            get {
                return ResourceManager.GetString("车2齿轮箱1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2齿轮箱2温度 的本地化字符串。
        /// </summary>
        internal static string 车2齿轮箱2温度 {
            get {
                return ResourceManager.GetString("车2齿轮箱2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2齿轮箱3温度 的本地化字符串。
        /// </summary>
        internal static string 车2齿轮箱3温度 {
            get {
                return ResourceManager.GetString("车2齿轮箱3温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2齿轮箱4温度 的本地化字符串。
        /// </summary>
        internal static string 车2齿轮箱4温度 {
            get {
                return ResourceManager.GetString("车2齿轮箱4温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2齿轮箱5温度 的本地化字符串。
        /// </summary>
        internal static string 车2齿轮箱5温度 {
            get {
                return ResourceManager.GetString("车2齿轮箱5温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2齿轮箱6温度 的本地化字符串。
        /// </summary>
        internal static string 车2齿轮箱6温度 {
            get {
                return ResourceManager.GetString("车2齿轮箱6温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2齿轮箱7温度 的本地化字符串。
        /// </summary>
        internal static string 车2齿轮箱7温度 {
            get {
                return ResourceManager.GetString("车2齿轮箱7温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车2齿轮箱8温度 的本地化字符串。
        /// </summary>
        internal static string 车2齿轮箱8温度 {
            get {
                return ResourceManager.GetString("车2齿轮箱8温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3制动力 的本地化字符串。
        /// </summary>
        internal static string 车3制动力 {
            get {
                return ResourceManager.GetString("车3制动力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3制动力百分比 的本地化字符串。
        /// </summary>
        internal static string 车3制动力百分比 {
            get {
                return ResourceManager.GetString("车3制动力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3水箱水量 的本地化字符串。
        /// </summary>
        internal static string 车3水箱水量 {
            get {
                return ResourceManager.GetString("车3水箱水量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3污物箱量 的本地化字符串。
        /// </summary>
        internal static string 车3污物箱量 {
            get {
                return ResourceManager.GetString("车3污物箱量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3温度 的本地化字符串。
        /// </summary>
        internal static string 车3温度 {
            get {
                return ResourceManager.GetString("车3温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3牵引力百分比 的本地化字符串。
        /// </summary>
        internal static string 车3牵引力百分比 {
            get {
                return ResourceManager.GetString("车3牵引力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3转向架温度 的本地化字符串。
        /// </summary>
        internal static string 车3转向架温度 {
            get {
                return ResourceManager.GetString("车3转向架温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3轴1温度 的本地化字符串。
        /// </summary>
        internal static string 车3轴1温度 {
            get {
                return ResourceManager.GetString("车3轴1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3轴2温度 的本地化字符串。
        /// </summary>
        internal static string 车3轴2温度 {
            get {
                return ResourceManager.GetString("车3轴2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3齿轮箱1温度 的本地化字符串。
        /// </summary>
        internal static string 车3齿轮箱1温度 {
            get {
                return ResourceManager.GetString("车3齿轮箱1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3齿轮箱2温度 的本地化字符串。
        /// </summary>
        internal static string 车3齿轮箱2温度 {
            get {
                return ResourceManager.GetString("车3齿轮箱2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3齿轮箱3温度 的本地化字符串。
        /// </summary>
        internal static string 车3齿轮箱3温度 {
            get {
                return ResourceManager.GetString("车3齿轮箱3温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3齿轮箱4温度 的本地化字符串。
        /// </summary>
        internal static string 车3齿轮箱4温度 {
            get {
                return ResourceManager.GetString("车3齿轮箱4温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3齿轮箱5温度 的本地化字符串。
        /// </summary>
        internal static string 车3齿轮箱5温度 {
            get {
                return ResourceManager.GetString("车3齿轮箱5温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3齿轮箱6温度 的本地化字符串。
        /// </summary>
        internal static string 车3齿轮箱6温度 {
            get {
                return ResourceManager.GetString("车3齿轮箱6温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3齿轮箱7温度 的本地化字符串。
        /// </summary>
        internal static string 车3齿轮箱7温度 {
            get {
                return ResourceManager.GetString("车3齿轮箱7温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车3齿轮箱8温度 的本地化字符串。
        /// </summary>
        internal static string 车3齿轮箱8温度 {
            get {
                return ResourceManager.GetString("车3齿轮箱8温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4制动力 的本地化字符串。
        /// </summary>
        internal static string 车4制动力 {
            get {
                return ResourceManager.GetString("车4制动力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4制动力百分比 的本地化字符串。
        /// </summary>
        internal static string 车4制动力百分比 {
            get {
                return ResourceManager.GetString("车4制动力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4压力传感器压力值 的本地化字符串。
        /// </summary>
        internal static string 车4压力传感器压力值 {
            get {
                return ResourceManager.GetString("车4压力传感器压力值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4水箱水量 的本地化字符串。
        /// </summary>
        internal static string 车4水箱水量 {
            get {
                return ResourceManager.GetString("车4水箱水量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4温度 的本地化字符串。
        /// </summary>
        internal static string 车4温度 {
            get {
                return ResourceManager.GetString("车4温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4牵引力百分比 的本地化字符串。
        /// </summary>
        internal static string 车4牵引力百分比 {
            get {
                return ResourceManager.GetString("车4牵引力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4转向架温度 的本地化字符串。
        /// </summary>
        internal static string 车4转向架温度 {
            get {
                return ResourceManager.GetString("车4转向架温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4轴1温度 的本地化字符串。
        /// </summary>
        internal static string 车4轴1温度 {
            get {
                return ResourceManager.GetString("车4轴1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4轴2温度 的本地化字符串。
        /// </summary>
        internal static string 车4轴2温度 {
            get {
                return ResourceManager.GetString("车4轴2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4齿轮箱1温度 的本地化字符串。
        /// </summary>
        internal static string 车4齿轮箱1温度 {
            get {
                return ResourceManager.GetString("车4齿轮箱1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4齿轮箱2温度 的本地化字符串。
        /// </summary>
        internal static string 车4齿轮箱2温度 {
            get {
                return ResourceManager.GetString("车4齿轮箱2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4齿轮箱3温度 的本地化字符串。
        /// </summary>
        internal static string 车4齿轮箱3温度 {
            get {
                return ResourceManager.GetString("车4齿轮箱3温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4齿轮箱4温度 的本地化字符串。
        /// </summary>
        internal static string 车4齿轮箱4温度 {
            get {
                return ResourceManager.GetString("车4齿轮箱4温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4齿轮箱5温度 的本地化字符串。
        /// </summary>
        internal static string 车4齿轮箱5温度 {
            get {
                return ResourceManager.GetString("车4齿轮箱5温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4齿轮箱6温度 的本地化字符串。
        /// </summary>
        internal static string 车4齿轮箱6温度 {
            get {
                return ResourceManager.GetString("车4齿轮箱6温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4齿轮箱7温度 的本地化字符串。
        /// </summary>
        internal static string 车4齿轮箱7温度 {
            get {
                return ResourceManager.GetString("车4齿轮箱7温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车4齿轮箱8温度 的本地化字符串。
        /// </summary>
        internal static string 车4齿轮箱8温度 {
            get {
                return ResourceManager.GetString("车4齿轮箱8温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5制动力 的本地化字符串。
        /// </summary>
        internal static string 车5制动力 {
            get {
                return ResourceManager.GetString("车5制动力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5制动力百分比 的本地化字符串。
        /// </summary>
        internal static string 车5制动力百分比 {
            get {
                return ResourceManager.GetString("车5制动力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5压力传感器压力值 的本地化字符串。
        /// </summary>
        internal static string 车5压力传感器压力值 {
            get {
                return ResourceManager.GetString("车5压力传感器压力值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5水箱水量 的本地化字符串。
        /// </summary>
        internal static string 车5水箱水量 {
            get {
                return ResourceManager.GetString("车5水箱水量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5污物箱量 的本地化字符串。
        /// </summary>
        internal static string 车5污物箱量 {
            get {
                return ResourceManager.GetString("车5污物箱量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5温度 的本地化字符串。
        /// </summary>
        internal static string 车5温度 {
            get {
                return ResourceManager.GetString("车5温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5牵引力百分比 的本地化字符串。
        /// </summary>
        internal static string 车5牵引力百分比 {
            get {
                return ResourceManager.GetString("车5牵引力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5转向架温度 的本地化字符串。
        /// </summary>
        internal static string 车5转向架温度 {
            get {
                return ResourceManager.GetString("车5转向架温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5轴1温度 的本地化字符串。
        /// </summary>
        internal static string 车5轴1温度 {
            get {
                return ResourceManager.GetString("车5轴1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5轴2温度 的本地化字符串。
        /// </summary>
        internal static string 车5轴2温度 {
            get {
                return ResourceManager.GetString("车5轴2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5齿轮箱1温度 的本地化字符串。
        /// </summary>
        internal static string 车5齿轮箱1温度 {
            get {
                return ResourceManager.GetString("车5齿轮箱1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5齿轮箱2温度 的本地化字符串。
        /// </summary>
        internal static string 车5齿轮箱2温度 {
            get {
                return ResourceManager.GetString("车5齿轮箱2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5齿轮箱3温度 的本地化字符串。
        /// </summary>
        internal static string 车5齿轮箱3温度 {
            get {
                return ResourceManager.GetString("车5齿轮箱3温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5齿轮箱4温度 的本地化字符串。
        /// </summary>
        internal static string 车5齿轮箱4温度 {
            get {
                return ResourceManager.GetString("车5齿轮箱4温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5齿轮箱5温度 的本地化字符串。
        /// </summary>
        internal static string 车5齿轮箱5温度 {
            get {
                return ResourceManager.GetString("车5齿轮箱5温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5齿轮箱6温度 的本地化字符串。
        /// </summary>
        internal static string 车5齿轮箱6温度 {
            get {
                return ResourceManager.GetString("车5齿轮箱6温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5齿轮箱7温度 的本地化字符串。
        /// </summary>
        internal static string 车5齿轮箱7温度 {
            get {
                return ResourceManager.GetString("车5齿轮箱7温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车5齿轮箱8温度 的本地化字符串。
        /// </summary>
        internal static string 车5齿轮箱8温度 {
            get {
                return ResourceManager.GetString("车5齿轮箱8温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6制动力 的本地化字符串。
        /// </summary>
        internal static string 车6制动力 {
            get {
                return ResourceManager.GetString("车6制动力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6制动力百分比 的本地化字符串。
        /// </summary>
        internal static string 车6制动力百分比 {
            get {
                return ResourceManager.GetString("车6制动力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6水箱水量 的本地化字符串。
        /// </summary>
        internal static string 车6水箱水量 {
            get {
                return ResourceManager.GetString("车6水箱水量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6污物箱量 的本地化字符串。
        /// </summary>
        internal static string 车6污物箱量 {
            get {
                return ResourceManager.GetString("车6污物箱量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6温度 的本地化字符串。
        /// </summary>
        internal static string 车6温度 {
            get {
                return ResourceManager.GetString("车6温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6牵引力百分比 的本地化字符串。
        /// </summary>
        internal static string 车6牵引力百分比 {
            get {
                return ResourceManager.GetString("车6牵引力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6转向架温度 的本地化字符串。
        /// </summary>
        internal static string 车6转向架温度 {
            get {
                return ResourceManager.GetString("车6转向架温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6轴1温度 的本地化字符串。
        /// </summary>
        internal static string 车6轴1温度 {
            get {
                return ResourceManager.GetString("车6轴1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6轴2温度 的本地化字符串。
        /// </summary>
        internal static string 车6轴2温度 {
            get {
                return ResourceManager.GetString("车6轴2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6齿轮箱1温度 的本地化字符串。
        /// </summary>
        internal static string 车6齿轮箱1温度 {
            get {
                return ResourceManager.GetString("车6齿轮箱1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6齿轮箱2温度 的本地化字符串。
        /// </summary>
        internal static string 车6齿轮箱2温度 {
            get {
                return ResourceManager.GetString("车6齿轮箱2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6齿轮箱3温度 的本地化字符串。
        /// </summary>
        internal static string 车6齿轮箱3温度 {
            get {
                return ResourceManager.GetString("车6齿轮箱3温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6齿轮箱4温度 的本地化字符串。
        /// </summary>
        internal static string 车6齿轮箱4温度 {
            get {
                return ResourceManager.GetString("车6齿轮箱4温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6齿轮箱5温度 的本地化字符串。
        /// </summary>
        internal static string 车6齿轮箱5温度 {
            get {
                return ResourceManager.GetString("车6齿轮箱5温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6齿轮箱6温度 的本地化字符串。
        /// </summary>
        internal static string 车6齿轮箱6温度 {
            get {
                return ResourceManager.GetString("车6齿轮箱6温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6齿轮箱7温度 的本地化字符串。
        /// </summary>
        internal static string 车6齿轮箱7温度 {
            get {
                return ResourceManager.GetString("车6齿轮箱7温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车6齿轮箱8温度 的本地化字符串。
        /// </summary>
        internal static string 车6齿轮箱8温度 {
            get {
                return ResourceManager.GetString("车6齿轮箱8温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7制动力 的本地化字符串。
        /// </summary>
        internal static string 车7制动力 {
            get {
                return ResourceManager.GetString("车7制动力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7制动力百分比 的本地化字符串。
        /// </summary>
        internal static string 车7制动力百分比 {
            get {
                return ResourceManager.GetString("车7制动力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7水箱水量 的本地化字符串。
        /// </summary>
        internal static string 车7水箱水量 {
            get {
                return ResourceManager.GetString("车7水箱水量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7污物箱量 的本地化字符串。
        /// </summary>
        internal static string 车7污物箱量 {
            get {
                return ResourceManager.GetString("车7污物箱量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7温度 的本地化字符串。
        /// </summary>
        internal static string 车7温度 {
            get {
                return ResourceManager.GetString("车7温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7牵引力百分比 的本地化字符串。
        /// </summary>
        internal static string 车7牵引力百分比 {
            get {
                return ResourceManager.GetString("车7牵引力百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7电压 的本地化字符串。
        /// </summary>
        internal static string 车7电压 {
            get {
                return ResourceManager.GetString("车7电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7电流 的本地化字符串。
        /// </summary>
        internal static string 车7电流 {
            get {
                return ResourceManager.GetString("车7电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7转向架温度 的本地化字符串。
        /// </summary>
        internal static string 车7转向架温度 {
            get {
                return ResourceManager.GetString("车7转向架温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7轴1温度 的本地化字符串。
        /// </summary>
        internal static string 车7轴1温度 {
            get {
                return ResourceManager.GetString("车7轴1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7轴2温度 的本地化字符串。
        /// </summary>
        internal static string 车7轴2温度 {
            get {
                return ResourceManager.GetString("车7轴2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7齿轮箱1温度 的本地化字符串。
        /// </summary>
        internal static string 车7齿轮箱1温度 {
            get {
                return ResourceManager.GetString("车7齿轮箱1温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7齿轮箱2温度 的本地化字符串。
        /// </summary>
        internal static string 车7齿轮箱2温度 {
            get {
                return ResourceManager.GetString("车7齿轮箱2温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7齿轮箱3温度 的本地化字符串。
        /// </summary>
        internal static string 车7齿轮箱3温度 {
            get {
                return ResourceManager.GetString("车7齿轮箱3温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7齿轮箱4温度 的本地化字符串。
        /// </summary>
        internal static string 车7齿轮箱4温度 {
            get {
                return ResourceManager.GetString("车7齿轮箱4温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7齿轮箱5温度 的本地化字符串。
        /// </summary>
        internal static string 车7齿轮箱5温度 {
            get {
                return ResourceManager.GetString("车7齿轮箱5温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7齿轮箱6温度 的本地化字符串。
        /// </summary>
        internal static string 车7齿轮箱6温度 {
            get {
                return ResourceManager.GetString("车7齿轮箱6温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7齿轮箱7温度 的本地化字符串。
        /// </summary>
        internal static string 车7齿轮箱7温度 {
            get {
                return ResourceManager.GetString("车7齿轮箱7温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车7齿轮箱8温度 的本地化字符串。
        /// </summary>
        internal static string 车7齿轮箱8温度 {
            get {
                return ResourceManager.GetString("车7齿轮箱8温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆加速度 的本地化字符串。
        /// </summary>
        internal static string 车辆加速度 {
            get {
                return ResourceManager.GetString("车辆加速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅助变流器电压 的本地化字符串。
        /// </summary>
        internal static string 辅助变流器电压 {
            get {
                return ResourceManager.GetString("辅助变流器电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度 的本地化字符串。
        /// </summary>
        internal static string 速度 {
            get {
                return ResourceManager.GetString("速度", resourceCulture);
            }
        }
    }
}
